-- =============================================================================================
-- BizApps Sales v6.1.x -- Metadata_Sync (one per release, generated by the build engineer)
-- =============================================================================================
-- Generated by `mj sync push --dir metadata --ci` against MJ_Sales_Pub: a database built from
-- migrations ONLY -- MJ core v6.1.0-edge.5, bizapps-common, bizapps-tasks, bizapps-accounting,
-- bizapps-orders, then this app's own migrations -- with no prior sync of this app's metadata.
-- The push reported 0 errors: 2 created, 12 updated, 3 deleted, 144 unchanged, 161 records.
--
-- Release seed coverage flagged 2 primaryKeys in no migration: the Activity Sync extension that
-- registers DealLinker with bizapps-common's engine, and the Sales Pipeline user view.
--
-- -- THE THREE DELETES ARE DELIBERATE, NOT DRIFT --------------------------------------------
--
--   EXEC [${mjSchema}].[spDeleteActionParam]  @ID = '5A1E5000-...-000000000102'
--   EXEC [${mjSchema}].[spDeleteAction]       @ID = '5A1E5000-...-000000000101'
--   EXEC [${mjSchema}].[spDeleteScheduledJob] @ID = '5A1E5000-...-000000000201'
--
-- These retire `Sales.SyncActivities`, superseded by bizapps-common's Activity Sync engine (the
-- DealLinker extension created above replaces it). All three IDs were seeded by
-- V202608251930__v5.2.x__Metadata_Sync.sql, so every host that installed 5.2.0 HAS them and needs
-- them removed. They are declared as tombstones in metadata/ -- `deleteRecord: { delete: true }` on
-- metadata/actions/.sales-actions.json and metadata/scheduled-jobs/.sales-scheduled-jobs.json,
-- added by 7b278dc "tombstone Sales.SyncActivities via deleteRecord" -- which is exactly the
-- mechanism MetadataSync provides for retiring a row that has already shipped.
--
-- -- SUBSTITUTION APPLIED TO THE GENERATOR'S OUTPUT -----------------------------------------
--
--   `[__mj]` -> `[${mjSchema}]`, in all 16 places it appeared.
--
-- Nothing else is rewritten, for two different reasons:
--
--   * `${flyway:defaultSchema}` does not appear because this file contains NO reference to this
--     app's own schema at all -- every statement is a core `__mj` call except the one
--     `spCreateActivitySyncExtension`. (Elsewhere in migrations/ this app uses BOTH forms:
--     `${flyway:defaultSchema}` 1,277 times and a literal `[__mj_BizAppsSales]` 296 times. The
--     question simply does not arise here.)
--   * `[__mj_BizAppsCommon]` is left literal. It is a DEPENDENCY's schema, not this app's, so it is
--     not this app's placeholder to rewrite -- `${flyway:defaultSchema}` would resolve it to
--     __mj_BizAppsSales and the call would fail.
-- =============================================================================================

-- SQL Logging Session
-- Session ID: bfccc621-6364-4735-912a-5af2908853d4
-- Started: 2026-09-02T05:11:39.568Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ_BizApps_Common: Activity Sync Extensions (core SP call only)
DECLARE @ID_86d22f4b UNIQUEIDENTIFIER,
@Name_86d22f4b NVARCHAR(200),
@Description_86d22f4b NVARCHAR(MAX),
@DriverClass_86d22f4b NVARCHAR(200),
@ActivitySyncConnectionID_86d22f4b UNIQUEIDENTIFIER,
@ActivitySyncProviderTypeID_86d22f4b UNIQUEIDENTIFIER,
@Sequence_86d22f4b INT,
@FailurePolicy_86d22f4b NVARCHAR(20),
@TimeoutMS_86d22f4b INT,
@IsEnabled_86d22f4b BIT,
@LastRunAt_86d22f4b DATETIMEOFFSET,
@LastError_86d22f4b NVARCHAR(MAX)
SET
  @ID_86d22f4b = 'a7c4e2b1-5d83-4f0a-9c1e-6b8d2f4a90c3'
SET
  @Name_86d22f4b = N'Sales.DealLinker'
SET
  @Description_86d22f4b = N'Inside the Activity write transaction, link matched open deals as Regarding. DealMatcher stays in sales; Common never learns what a deal is.'
SET
  @DriverClass_86d22f4b = N'Sales.DealLinker'
SET
  @Sequence_86d22f4b = 10
SET
  @FailurePolicy_86d22f4b = N'Skip'
SET
  @TimeoutMS_86d22f4b = 5000
SET
  @IsEnabled_86d22f4b = 1
EXEC [__mj_BizAppsCommon].spCreateActivitySyncExtension @ID = @ID_86d22f4b,
  @Name = @Name_86d22f4b,
  @Description = @Description_86d22f4b,
  @DriverClass = @DriverClass_86d22f4b,
  @ActivitySyncConnectionID = @ActivitySyncConnectionID_86d22f4b,
  @ActivitySyncConnectionID_Clear = 1,
  @ActivitySyncProviderTypeID = @ActivitySyncProviderTypeID_86d22f4b,
  @ActivitySyncProviderTypeID_Clear = 1,
  @Sequence = @Sequence_86d22f4b,
  @FailurePolicy = @FailurePolicy_86d22f4b,
  @TimeoutMS = @TimeoutMS_86d22f4b,
  @IsEnabled = @IsEnabled_86d22f4b,
  @LastRunAt = @LastRunAt_86d22f4b,
  @LastRunAt_Clear = 1,
  @LastError = @LastError_86d22f4b,
  @LastError_Clear = 1;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_d1702abc NVARCHAR(255),
@Description_d1702abc NVARCHAR(MAX),
@AutoUpdateDescription_d1702abc BIT,
@IsPrimaryKey_d1702abc BIT,
@IsUnique_d1702abc BIT,
@Category_d1702abc NVARCHAR(255),
@ValueListType_d1702abc NVARCHAR(20),
@ExtendedType_d1702abc NVARCHAR(50),
@CodeType_d1702abc NVARCHAR(50),
@DefaultInView_d1702abc BIT,
@ViewCellTemplate_d1702abc NVARCHAR(MAX),
@DefaultColumnWidth_d1702abc INT,
@AllowUpdateAPI_d1702abc BIT,
@AllowUpdateInView_d1702abc BIT,
@IncludeInUserSearchAPI_d1702abc BIT,
@FullTextSearchEnabled_d1702abc BIT,
@UserSearchParamFormatAPI_d1702abc NVARCHAR(500),
@IncludeInGeneratedForm_d1702abc BIT,
@GeneratedFormSection_d1702abc NVARCHAR(10),
@IsNameField_d1702abc BIT,
@RelatedEntityID_d1702abc UNIQUEIDENTIFIER,
@RelatedEntityFieldName_d1702abc NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_d1702abc BIT,
@RelatedEntityNameFieldMap_d1702abc NVARCHAR(255),
@RelatedEntityDisplayType_d1702abc NVARCHAR(20),
@EntityIDFieldName_d1702abc NVARCHAR(100),
@ScopeDefault_d1702abc NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_d1702abc BIT,
@ValuesToPackWithSchema_d1702abc NVARCHAR(10),
@Status_d1702abc NVARCHAR(25),
@AutoUpdateIsNameField_d1702abc BIT,
@AutoUpdateDefaultInView_d1702abc BIT,
@AutoUpdateCategory_d1702abc BIT,
@AutoUpdateDisplayName_d1702abc BIT,
@AutoUpdateIncludeInUserSearchAPI_d1702abc BIT,
@Encrypt_d1702abc BIT,
@EncryptionKeyID_d1702abc UNIQUEIDENTIFIER,
@AllowDecryptInAPI_d1702abc BIT,
@SendEncryptedValue_d1702abc BIT,
@IsSoftPrimaryKey_d1702abc BIT,
@IsSoftForeignKey_d1702abc BIT,
@RelatedEntityJoinFields_d1702abc NVARCHAR(MAX),
@JSONType_d1702abc NVARCHAR(255),
@JSONTypeIsArray_d1702abc BIT,
@JSONTypeDefinition_d1702abc NVARCHAR(MAX),
@UserSearchPredicateAPI_d1702abc NVARCHAR(20),
@AutoUpdateUserSearchPredicate_d1702abc BIT,
@AutoUpdateFullTextSearch_d1702abc BIT,
@AutoUpdateExtendedType_d1702abc BIT,
@IsComputed_d1702abc BIT,
@EmbeddedRecord_d1702abc NVARCHAR(MAX),
@Configuration_d1702abc NVARCHAR(MAX),
@ID_d1702abc UNIQUEIDENTIFIER
SET
  @DisplayName_d1702abc = N'Deal Number'
SET
  @AutoUpdateDescription_d1702abc = 1
SET
  @IsPrimaryKey_d1702abc = 0
SET
  @IsUnique_d1702abc = 1
SET
  @ValueListType_d1702abc = N'None'
SET
  @DefaultInView_d1702abc = 1
SET
  @DefaultColumnWidth_d1702abc = 150
SET
  @AllowUpdateAPI_d1702abc = 1
SET
  @AllowUpdateInView_d1702abc = 1
SET
  @IncludeInUserSearchAPI_d1702abc = 0
SET
  @FullTextSearchEnabled_d1702abc = 0
SET
  @IncludeInGeneratedForm_d1702abc = 1
SET
  @GeneratedFormSection_d1702abc = N'Details'
SET
  @IsNameField_d1702abc = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_d1702abc = 0
SET
  @RelatedEntityDisplayType_d1702abc = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_d1702abc = 1
SET
  @ValuesToPackWithSchema_d1702abc = N'Auto'
SET
  @Status_d1702abc = N'Active'
SET
  @AutoUpdateIsNameField_d1702abc = 1
SET
  @AutoUpdateDefaultInView_d1702abc = 1
SET
  @AutoUpdateCategory_d1702abc = 1
SET
  @AutoUpdateDisplayName_d1702abc = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_d1702abc = 1
SET
  @Encrypt_d1702abc = 0
SET
  @AllowDecryptInAPI_d1702abc = 0
SET
  @SendEncryptedValue_d1702abc = 0
SET
  @IsSoftPrimaryKey_d1702abc = 0
SET
  @IsSoftForeignKey_d1702abc = 0
SET
  @JSONTypeIsArray_d1702abc = 0
SET
  @UserSearchPredicateAPI_d1702abc = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_d1702abc = 1
SET
  @AutoUpdateFullTextSearch_d1702abc = 1
SET
  @AutoUpdateExtendedType_d1702abc = 1
SET
  @IsComputed_d1702abc = 0
SET
  @ID_d1702abc = '939FFD49-39DA-4200-BE2E-906F14FE50E1' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_d1702abc,
  @Description = @Description_d1702abc,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_d1702abc,
  @IsPrimaryKey = @IsPrimaryKey_d1702abc,
  @IsUnique = @IsUnique_d1702abc,
  @Category = @Category_d1702abc,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_d1702abc,
  @ExtendedType = @ExtendedType_d1702abc,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_d1702abc,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_d1702abc,
  @ViewCellTemplate = @ViewCellTemplate_d1702abc,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_d1702abc,
  @AllowUpdateAPI = @AllowUpdateAPI_d1702abc,
  @AllowUpdateInView = @AllowUpdateInView_d1702abc,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_d1702abc,
  @FullTextSearchEnabled = @FullTextSearchEnabled_d1702abc,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_d1702abc,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_d1702abc,
  @GeneratedFormSection = @GeneratedFormSection_d1702abc,
  @IsNameField = @IsNameField_d1702abc,
  @RelatedEntityID = @RelatedEntityID_d1702abc,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_d1702abc,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_d1702abc,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_d1702abc,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_d1702abc,
  @EntityIDFieldName = @EntityIDFieldName_d1702abc,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_d1702abc,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_d1702abc,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_d1702abc,
  @Status = @Status_d1702abc,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_d1702abc,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_d1702abc,
  @AutoUpdateCategory = @AutoUpdateCategory_d1702abc,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_d1702abc,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_d1702abc,
  @Encrypt = @Encrypt_d1702abc,
  @EncryptionKeyID = @EncryptionKeyID_d1702abc,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_d1702abc,
  @SendEncryptedValue = @SendEncryptedValue_d1702abc,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_d1702abc,
  @IsSoftForeignKey = @IsSoftForeignKey_d1702abc,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_d1702abc,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_d1702abc,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_d1702abc,
  @JSONTypeDefinition = @JSONTypeDefinition_d1702abc,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_d1702abc,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_d1702abc,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_d1702abc,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_d1702abc,
  @IsComputed = @IsComputed_d1702abc,
  @EmbeddedRecord = @EmbeddedRecord_d1702abc,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_d1702abc,
  @Configuration_Clear = 1,
  @ID = @ID_d1702abc;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_06df379f NVARCHAR(255),
@Description_06df379f NVARCHAR(MAX),
@AutoUpdateDescription_06df379f BIT,
@IsPrimaryKey_06df379f BIT,
@IsUnique_06df379f BIT,
@Category_06df379f NVARCHAR(255),
@ValueListType_06df379f NVARCHAR(20),
@ExtendedType_06df379f NVARCHAR(50),
@CodeType_06df379f NVARCHAR(50),
@DefaultInView_06df379f BIT,
@ViewCellTemplate_06df379f NVARCHAR(MAX),
@DefaultColumnWidth_06df379f INT,
@AllowUpdateAPI_06df379f BIT,
@AllowUpdateInView_06df379f BIT,
@IncludeInUserSearchAPI_06df379f BIT,
@FullTextSearchEnabled_06df379f BIT,
@UserSearchParamFormatAPI_06df379f NVARCHAR(500),
@IncludeInGeneratedForm_06df379f BIT,
@GeneratedFormSection_06df379f NVARCHAR(10),
@IsNameField_06df379f BIT,
@RelatedEntityID_06df379f UNIQUEIDENTIFIER,
@RelatedEntityFieldName_06df379f NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_06df379f BIT,
@RelatedEntityNameFieldMap_06df379f NVARCHAR(255),
@RelatedEntityDisplayType_06df379f NVARCHAR(20),
@EntityIDFieldName_06df379f NVARCHAR(100),
@ScopeDefault_06df379f NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_06df379f BIT,
@ValuesToPackWithSchema_06df379f NVARCHAR(10),
@Status_06df379f NVARCHAR(25),
@AutoUpdateIsNameField_06df379f BIT,
@AutoUpdateDefaultInView_06df379f BIT,
@AutoUpdateCategory_06df379f BIT,
@AutoUpdateDisplayName_06df379f BIT,
@AutoUpdateIncludeInUserSearchAPI_06df379f BIT,
@Encrypt_06df379f BIT,
@EncryptionKeyID_06df379f UNIQUEIDENTIFIER,
@AllowDecryptInAPI_06df379f BIT,
@SendEncryptedValue_06df379f BIT,
@IsSoftPrimaryKey_06df379f BIT,
@IsSoftForeignKey_06df379f BIT,
@RelatedEntityJoinFields_06df379f NVARCHAR(MAX),
@JSONType_06df379f NVARCHAR(255),
@JSONTypeIsArray_06df379f BIT,
@JSONTypeDefinition_06df379f NVARCHAR(MAX),
@UserSearchPredicateAPI_06df379f NVARCHAR(20),
@AutoUpdateUserSearchPredicate_06df379f BIT,
@AutoUpdateFullTextSearch_06df379f BIT,
@AutoUpdateExtendedType_06df379f BIT,
@IsComputed_06df379f BIT,
@EmbeddedRecord_06df379f NVARCHAR(MAX),
@Configuration_06df379f NVARCHAR(MAX),
@ID_06df379f UNIQUEIDENTIFIER
SET
  @DisplayName_06df379f = N'Pipeline'
SET
  @AutoUpdateDescription_06df379f = 1
SET
  @IsPrimaryKey_06df379f = 0
SET
  @IsUnique_06df379f = 0
SET
  @ValueListType_06df379f = N'None'
SET
  @DefaultInView_06df379f = 1
SET
  @DefaultColumnWidth_06df379f = 150
SET
  @AllowUpdateAPI_06df379f = 0
SET
  @AllowUpdateInView_06df379f = 1
SET
  @IncludeInUserSearchAPI_06df379f = 0
SET
  @FullTextSearchEnabled_06df379f = 0
SET
  @IncludeInGeneratedForm_06df379f = 1
SET
  @GeneratedFormSection_06df379f = N'Details'
SET
  @IsNameField_06df379f = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_06df379f = 0
SET
  @RelatedEntityDisplayType_06df379f = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_06df379f = 1
SET
  @ValuesToPackWithSchema_06df379f = N'Auto'
SET
  @Status_06df379f = N'Active'
SET
  @AutoUpdateIsNameField_06df379f = 1
SET
  @AutoUpdateDefaultInView_06df379f = 1
SET
  @AutoUpdateCategory_06df379f = 1
SET
  @AutoUpdateDisplayName_06df379f = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_06df379f = 1
SET
  @Encrypt_06df379f = 0
SET
  @AllowDecryptInAPI_06df379f = 0
SET
  @SendEncryptedValue_06df379f = 0
SET
  @IsSoftPrimaryKey_06df379f = 0
SET
  @IsSoftForeignKey_06df379f = 0
SET
  @JSONTypeIsArray_06df379f = 0
SET
  @UserSearchPredicateAPI_06df379f = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_06df379f = 1
SET
  @AutoUpdateFullTextSearch_06df379f = 1
SET
  @AutoUpdateExtendedType_06df379f = 1
SET
  @IsComputed_06df379f = 0
SET
  @ID_06df379f = '2AA2DC76-847E-452C-B01C-8CC4082921B2' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_06df379f,
  @Description = @Description_06df379f,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_06df379f,
  @IsPrimaryKey = @IsPrimaryKey_06df379f,
  @IsUnique = @IsUnique_06df379f,
  @Category = @Category_06df379f,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_06df379f,
  @ExtendedType = @ExtendedType_06df379f,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_06df379f,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_06df379f,
  @ViewCellTemplate = @ViewCellTemplate_06df379f,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_06df379f,
  @AllowUpdateAPI = @AllowUpdateAPI_06df379f,
  @AllowUpdateInView = @AllowUpdateInView_06df379f,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_06df379f,
  @FullTextSearchEnabled = @FullTextSearchEnabled_06df379f,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_06df379f,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_06df379f,
  @GeneratedFormSection = @GeneratedFormSection_06df379f,
  @IsNameField = @IsNameField_06df379f,
  @RelatedEntityID = @RelatedEntityID_06df379f,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_06df379f,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_06df379f,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_06df379f,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_06df379f,
  @EntityIDFieldName = @EntityIDFieldName_06df379f,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_06df379f,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_06df379f,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_06df379f,
  @Status = @Status_06df379f,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_06df379f,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_06df379f,
  @AutoUpdateCategory = @AutoUpdateCategory_06df379f,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_06df379f,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_06df379f,
  @Encrypt = @Encrypt_06df379f,
  @EncryptionKeyID = @EncryptionKeyID_06df379f,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_06df379f,
  @SendEncryptedValue = @SendEncryptedValue_06df379f,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_06df379f,
  @IsSoftForeignKey = @IsSoftForeignKey_06df379f,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_06df379f,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_06df379f,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_06df379f,
  @JSONTypeDefinition = @JSONTypeDefinition_06df379f,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_06df379f,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_06df379f,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_06df379f,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_06df379f,
  @IsComputed = @IsComputed_06df379f,
  @EmbeddedRecord = @EmbeddedRecord_06df379f,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_06df379f,
  @Configuration_Clear = 1,
  @ID = @ID_06df379f;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_e24b00ce NVARCHAR(255),
@Description_e24b00ce NVARCHAR(MAX),
@AutoUpdateDescription_e24b00ce BIT,
@IsPrimaryKey_e24b00ce BIT,
@IsUnique_e24b00ce BIT,
@Category_e24b00ce NVARCHAR(255),
@ValueListType_e24b00ce NVARCHAR(20),
@ExtendedType_e24b00ce NVARCHAR(50),
@CodeType_e24b00ce NVARCHAR(50),
@DefaultInView_e24b00ce BIT,
@ViewCellTemplate_e24b00ce NVARCHAR(MAX),
@DefaultColumnWidth_e24b00ce INT,
@AllowUpdateAPI_e24b00ce BIT,
@AllowUpdateInView_e24b00ce BIT,
@IncludeInUserSearchAPI_e24b00ce BIT,
@FullTextSearchEnabled_e24b00ce BIT,
@UserSearchParamFormatAPI_e24b00ce NVARCHAR(500),
@IncludeInGeneratedForm_e24b00ce BIT,
@GeneratedFormSection_e24b00ce NVARCHAR(10),
@IsNameField_e24b00ce BIT,
@RelatedEntityID_e24b00ce UNIQUEIDENTIFIER,
@RelatedEntityFieldName_e24b00ce NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_e24b00ce BIT,
@RelatedEntityNameFieldMap_e24b00ce NVARCHAR(255),
@RelatedEntityDisplayType_e24b00ce NVARCHAR(20),
@EntityIDFieldName_e24b00ce NVARCHAR(100),
@ScopeDefault_e24b00ce NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_e24b00ce BIT,
@ValuesToPackWithSchema_e24b00ce NVARCHAR(10),
@Status_e24b00ce NVARCHAR(25),
@AutoUpdateIsNameField_e24b00ce BIT,
@AutoUpdateDefaultInView_e24b00ce BIT,
@AutoUpdateCategory_e24b00ce BIT,
@AutoUpdateDisplayName_e24b00ce BIT,
@AutoUpdateIncludeInUserSearchAPI_e24b00ce BIT,
@Encrypt_e24b00ce BIT,
@EncryptionKeyID_e24b00ce UNIQUEIDENTIFIER,
@AllowDecryptInAPI_e24b00ce BIT,
@SendEncryptedValue_e24b00ce BIT,
@IsSoftPrimaryKey_e24b00ce BIT,
@IsSoftForeignKey_e24b00ce BIT,
@RelatedEntityJoinFields_e24b00ce NVARCHAR(MAX),
@JSONType_e24b00ce NVARCHAR(255),
@JSONTypeIsArray_e24b00ce BIT,
@JSONTypeDefinition_e24b00ce NVARCHAR(MAX),
@UserSearchPredicateAPI_e24b00ce NVARCHAR(20),
@AutoUpdateUserSearchPredicate_e24b00ce BIT,
@AutoUpdateFullTextSearch_e24b00ce BIT,
@AutoUpdateExtendedType_e24b00ce BIT,
@IsComputed_e24b00ce BIT,
@EmbeddedRecord_e24b00ce NVARCHAR(MAX),
@Configuration_e24b00ce NVARCHAR(MAX),
@ID_e24b00ce UNIQUEIDENTIFIER
SET
  @DisplayName_e24b00ce = N'Account'
SET
  @AutoUpdateDescription_e24b00ce = 1
SET
  @IsPrimaryKey_e24b00ce = 0
SET
  @IsUnique_e24b00ce = 0
SET
  @ValueListType_e24b00ce = N'None'
SET
  @DefaultInView_e24b00ce = 1
SET
  @DefaultColumnWidth_e24b00ce = 150
SET
  @AllowUpdateAPI_e24b00ce = 0
SET
  @AllowUpdateInView_e24b00ce = 1
SET
  @IncludeInUserSearchAPI_e24b00ce = 0
SET
  @FullTextSearchEnabled_e24b00ce = 0
SET
  @IncludeInGeneratedForm_e24b00ce = 1
SET
  @GeneratedFormSection_e24b00ce = N'Details'
SET
  @IsNameField_e24b00ce = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_e24b00ce = 0
SET
  @RelatedEntityDisplayType_e24b00ce = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_e24b00ce = 1
SET
  @ValuesToPackWithSchema_e24b00ce = N'Auto'
SET
  @Status_e24b00ce = N'Active'
SET
  @AutoUpdateIsNameField_e24b00ce = 1
SET
  @AutoUpdateDefaultInView_e24b00ce = 1
SET
  @AutoUpdateCategory_e24b00ce = 1
SET
  @AutoUpdateDisplayName_e24b00ce = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_e24b00ce = 1
SET
  @Encrypt_e24b00ce = 0
SET
  @AllowDecryptInAPI_e24b00ce = 0
SET
  @SendEncryptedValue_e24b00ce = 0
SET
  @IsSoftPrimaryKey_e24b00ce = 0
SET
  @IsSoftForeignKey_e24b00ce = 0
SET
  @JSONTypeIsArray_e24b00ce = 0
SET
  @UserSearchPredicateAPI_e24b00ce = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_e24b00ce = 1
SET
  @AutoUpdateFullTextSearch_e24b00ce = 1
SET
  @AutoUpdateExtendedType_e24b00ce = 1
SET
  @IsComputed_e24b00ce = 0
SET
  @ID_e24b00ce = '94114B63-4A39-4A2C-B774-16651DCC7944' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_e24b00ce,
  @Description = @Description_e24b00ce,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_e24b00ce,
  @IsPrimaryKey = @IsPrimaryKey_e24b00ce,
  @IsUnique = @IsUnique_e24b00ce,
  @Category = @Category_e24b00ce,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_e24b00ce,
  @ExtendedType = @ExtendedType_e24b00ce,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_e24b00ce,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_e24b00ce,
  @ViewCellTemplate = @ViewCellTemplate_e24b00ce,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_e24b00ce,
  @AllowUpdateAPI = @AllowUpdateAPI_e24b00ce,
  @AllowUpdateInView = @AllowUpdateInView_e24b00ce,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_e24b00ce,
  @FullTextSearchEnabled = @FullTextSearchEnabled_e24b00ce,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_e24b00ce,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_e24b00ce,
  @GeneratedFormSection = @GeneratedFormSection_e24b00ce,
  @IsNameField = @IsNameField_e24b00ce,
  @RelatedEntityID = @RelatedEntityID_e24b00ce,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_e24b00ce,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_e24b00ce,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_e24b00ce,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_e24b00ce,
  @EntityIDFieldName = @EntityIDFieldName_e24b00ce,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_e24b00ce,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_e24b00ce,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_e24b00ce,
  @Status = @Status_e24b00ce,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_e24b00ce,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_e24b00ce,
  @AutoUpdateCategory = @AutoUpdateCategory_e24b00ce,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_e24b00ce,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_e24b00ce,
  @Encrypt = @Encrypt_e24b00ce,
  @EncryptionKeyID = @EncryptionKeyID_e24b00ce,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_e24b00ce,
  @SendEncryptedValue = @SendEncryptedValue_e24b00ce,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_e24b00ce,
  @IsSoftForeignKey = @IsSoftForeignKey_e24b00ce,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_e24b00ce,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_e24b00ce,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_e24b00ce,
  @JSONTypeDefinition = @JSONTypeDefinition_e24b00ce,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_e24b00ce,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_e24b00ce,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_e24b00ce,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_e24b00ce,
  @IsComputed = @IsComputed_e24b00ce,
  @EmbeddedRecord = @EmbeddedRecord_e24b00ce,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_e24b00ce,
  @Configuration_Clear = 1,
  @ID = @ID_e24b00ce;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_95cc17cd NVARCHAR(255),
@Description_95cc17cd NVARCHAR(MAX),
@AutoUpdateDescription_95cc17cd BIT,
@IsPrimaryKey_95cc17cd BIT,
@IsUnique_95cc17cd BIT,
@Category_95cc17cd NVARCHAR(255),
@ValueListType_95cc17cd NVARCHAR(20),
@ExtendedType_95cc17cd NVARCHAR(50),
@CodeType_95cc17cd NVARCHAR(50),
@DefaultInView_95cc17cd BIT,
@ViewCellTemplate_95cc17cd NVARCHAR(MAX),
@DefaultColumnWidth_95cc17cd INT,
@AllowUpdateAPI_95cc17cd BIT,
@AllowUpdateInView_95cc17cd BIT,
@IncludeInUserSearchAPI_95cc17cd BIT,
@FullTextSearchEnabled_95cc17cd BIT,
@UserSearchParamFormatAPI_95cc17cd NVARCHAR(500),
@IncludeInGeneratedForm_95cc17cd BIT,
@GeneratedFormSection_95cc17cd NVARCHAR(10),
@IsNameField_95cc17cd BIT,
@RelatedEntityID_95cc17cd UNIQUEIDENTIFIER,
@RelatedEntityFieldName_95cc17cd NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_95cc17cd BIT,
@RelatedEntityNameFieldMap_95cc17cd NVARCHAR(255),
@RelatedEntityDisplayType_95cc17cd NVARCHAR(20),
@EntityIDFieldName_95cc17cd NVARCHAR(100),
@ScopeDefault_95cc17cd NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_95cc17cd BIT,
@ValuesToPackWithSchema_95cc17cd NVARCHAR(10),
@Status_95cc17cd NVARCHAR(25),
@AutoUpdateIsNameField_95cc17cd BIT,
@AutoUpdateDefaultInView_95cc17cd BIT,
@AutoUpdateCategory_95cc17cd BIT,
@AutoUpdateDisplayName_95cc17cd BIT,
@AutoUpdateIncludeInUserSearchAPI_95cc17cd BIT,
@Encrypt_95cc17cd BIT,
@EncryptionKeyID_95cc17cd UNIQUEIDENTIFIER,
@AllowDecryptInAPI_95cc17cd BIT,
@SendEncryptedValue_95cc17cd BIT,
@IsSoftPrimaryKey_95cc17cd BIT,
@IsSoftForeignKey_95cc17cd BIT,
@RelatedEntityJoinFields_95cc17cd NVARCHAR(MAX),
@JSONType_95cc17cd NVARCHAR(255),
@JSONTypeIsArray_95cc17cd BIT,
@JSONTypeDefinition_95cc17cd NVARCHAR(MAX),
@UserSearchPredicateAPI_95cc17cd NVARCHAR(20),
@AutoUpdateUserSearchPredicate_95cc17cd BIT,
@AutoUpdateFullTextSearch_95cc17cd BIT,
@AutoUpdateExtendedType_95cc17cd BIT,
@IsComputed_95cc17cd BIT,
@EmbeddedRecord_95cc17cd NVARCHAR(MAX),
@Configuration_95cc17cd NVARCHAR(MAX),
@ID_95cc17cd UNIQUEIDENTIFIER
SET
  @DisplayName_95cc17cd = N'Pipeline Stage'
SET
  @AutoUpdateDescription_95cc17cd = 1
SET
  @IsPrimaryKey_95cc17cd = 0
SET
  @IsUnique_95cc17cd = 0
SET
  @ValueListType_95cc17cd = N'None'
SET
  @DefaultInView_95cc17cd = 1
SET
  @DefaultColumnWidth_95cc17cd = 150
SET
  @AllowUpdateAPI_95cc17cd = 0
SET
  @AllowUpdateInView_95cc17cd = 1
SET
  @IncludeInUserSearchAPI_95cc17cd = 0
SET
  @FullTextSearchEnabled_95cc17cd = 0
SET
  @IncludeInGeneratedForm_95cc17cd = 1
SET
  @GeneratedFormSection_95cc17cd = N'Details'
SET
  @IsNameField_95cc17cd = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_95cc17cd = 0
SET
  @RelatedEntityDisplayType_95cc17cd = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_95cc17cd = 1
SET
  @ValuesToPackWithSchema_95cc17cd = N'Auto'
SET
  @Status_95cc17cd = N'Active'
SET
  @AutoUpdateIsNameField_95cc17cd = 1
SET
  @AutoUpdateDefaultInView_95cc17cd = 1
SET
  @AutoUpdateCategory_95cc17cd = 1
SET
  @AutoUpdateDisplayName_95cc17cd = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_95cc17cd = 1
SET
  @Encrypt_95cc17cd = 0
SET
  @AllowDecryptInAPI_95cc17cd = 0
SET
  @SendEncryptedValue_95cc17cd = 0
SET
  @IsSoftPrimaryKey_95cc17cd = 0
SET
  @IsSoftForeignKey_95cc17cd = 0
SET
  @JSONTypeIsArray_95cc17cd = 0
SET
  @UserSearchPredicateAPI_95cc17cd = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_95cc17cd = 1
SET
  @AutoUpdateFullTextSearch_95cc17cd = 1
SET
  @AutoUpdateExtendedType_95cc17cd = 1
SET
  @IsComputed_95cc17cd = 0
SET
  @ID_95cc17cd = 'E343398A-30E1-454C-AD9B-9B24D43ACCA3' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_95cc17cd,
  @Description = @Description_95cc17cd,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_95cc17cd,
  @IsPrimaryKey = @IsPrimaryKey_95cc17cd,
  @IsUnique = @IsUnique_95cc17cd,
  @Category = @Category_95cc17cd,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_95cc17cd,
  @ExtendedType = @ExtendedType_95cc17cd,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_95cc17cd,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_95cc17cd,
  @ViewCellTemplate = @ViewCellTemplate_95cc17cd,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_95cc17cd,
  @AllowUpdateAPI = @AllowUpdateAPI_95cc17cd,
  @AllowUpdateInView = @AllowUpdateInView_95cc17cd,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_95cc17cd,
  @FullTextSearchEnabled = @FullTextSearchEnabled_95cc17cd,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_95cc17cd,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_95cc17cd,
  @GeneratedFormSection = @GeneratedFormSection_95cc17cd,
  @IsNameField = @IsNameField_95cc17cd,
  @RelatedEntityID = @RelatedEntityID_95cc17cd,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_95cc17cd,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_95cc17cd,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_95cc17cd,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_95cc17cd,
  @EntityIDFieldName = @EntityIDFieldName_95cc17cd,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_95cc17cd,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_95cc17cd,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_95cc17cd,
  @Status = @Status_95cc17cd,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_95cc17cd,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_95cc17cd,
  @AutoUpdateCategory = @AutoUpdateCategory_95cc17cd,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_95cc17cd,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_95cc17cd,
  @Encrypt = @Encrypt_95cc17cd,
  @EncryptionKeyID = @EncryptionKeyID_95cc17cd,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_95cc17cd,
  @SendEncryptedValue = @SendEncryptedValue_95cc17cd,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_95cc17cd,
  @IsSoftForeignKey = @IsSoftForeignKey_95cc17cd,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_95cc17cd,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_95cc17cd,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_95cc17cd,
  @JSONTypeDefinition = @JSONTypeDefinition_95cc17cd,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_95cc17cd,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_95cc17cd,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_95cc17cd,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_95cc17cd,
  @IsComputed = @IsComputed_95cc17cd,
  @EmbeddedRecord = @EmbeddedRecord_95cc17cd,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_95cc17cd,
  @Configuration_Clear = 1,
  @ID = @ID_95cc17cd;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_51a02b68 NVARCHAR(255),
@Description_51a02b68 NVARCHAR(MAX),
@AutoUpdateDescription_51a02b68 BIT,
@IsPrimaryKey_51a02b68 BIT,
@IsUnique_51a02b68 BIT,
@Category_51a02b68 NVARCHAR(255),
@ValueListType_51a02b68 NVARCHAR(20),
@ExtendedType_51a02b68 NVARCHAR(50),
@CodeType_51a02b68 NVARCHAR(50),
@DefaultInView_51a02b68 BIT,
@ViewCellTemplate_51a02b68 NVARCHAR(MAX),
@DefaultColumnWidth_51a02b68 INT,
@AllowUpdateAPI_51a02b68 BIT,
@AllowUpdateInView_51a02b68 BIT,
@IncludeInUserSearchAPI_51a02b68 BIT,
@FullTextSearchEnabled_51a02b68 BIT,
@UserSearchParamFormatAPI_51a02b68 NVARCHAR(500),
@IncludeInGeneratedForm_51a02b68 BIT,
@GeneratedFormSection_51a02b68 NVARCHAR(10),
@IsNameField_51a02b68 BIT,
@RelatedEntityID_51a02b68 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_51a02b68 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_51a02b68 BIT,
@RelatedEntityNameFieldMap_51a02b68 NVARCHAR(255),
@RelatedEntityDisplayType_51a02b68 NVARCHAR(20),
@EntityIDFieldName_51a02b68 NVARCHAR(100),
@ScopeDefault_51a02b68 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_51a02b68 BIT,
@ValuesToPackWithSchema_51a02b68 NVARCHAR(10),
@Status_51a02b68 NVARCHAR(25),
@AutoUpdateIsNameField_51a02b68 BIT,
@AutoUpdateDefaultInView_51a02b68 BIT,
@AutoUpdateCategory_51a02b68 BIT,
@AutoUpdateDisplayName_51a02b68 BIT,
@AutoUpdateIncludeInUserSearchAPI_51a02b68 BIT,
@Encrypt_51a02b68 BIT,
@EncryptionKeyID_51a02b68 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_51a02b68 BIT,
@SendEncryptedValue_51a02b68 BIT,
@IsSoftPrimaryKey_51a02b68 BIT,
@IsSoftForeignKey_51a02b68 BIT,
@RelatedEntityJoinFields_51a02b68 NVARCHAR(MAX),
@JSONType_51a02b68 NVARCHAR(255),
@JSONTypeIsArray_51a02b68 BIT,
@JSONTypeDefinition_51a02b68 NVARCHAR(MAX),
@UserSearchPredicateAPI_51a02b68 NVARCHAR(20),
@AutoUpdateUserSearchPredicate_51a02b68 BIT,
@AutoUpdateFullTextSearch_51a02b68 BIT,
@AutoUpdateExtendedType_51a02b68 BIT,
@IsComputed_51a02b68 BIT,
@EmbeddedRecord_51a02b68 NVARCHAR(MAX),
@Configuration_51a02b68 NVARCHAR(MAX),
@ID_51a02b68 UNIQUEIDENTIFIER
SET
  @DisplayName_51a02b68 = N'Deal Status Type'
SET
  @AutoUpdateDescription_51a02b68 = 1
SET
  @IsPrimaryKey_51a02b68 = 0
SET
  @IsUnique_51a02b68 = 0
SET
  @ValueListType_51a02b68 = N'None'
SET
  @DefaultInView_51a02b68 = 1
SET
  @DefaultColumnWidth_51a02b68 = 150
SET
  @AllowUpdateAPI_51a02b68 = 0
SET
  @AllowUpdateInView_51a02b68 = 1
SET
  @IncludeInUserSearchAPI_51a02b68 = 0
SET
  @FullTextSearchEnabled_51a02b68 = 0
SET
  @IncludeInGeneratedForm_51a02b68 = 1
SET
  @GeneratedFormSection_51a02b68 = N'Details'
SET
  @IsNameField_51a02b68 = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_51a02b68 = 0
SET
  @RelatedEntityDisplayType_51a02b68 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_51a02b68 = 1
SET
  @ValuesToPackWithSchema_51a02b68 = N'Auto'
SET
  @Status_51a02b68 = N'Active'
SET
  @AutoUpdateIsNameField_51a02b68 = 1
SET
  @AutoUpdateDefaultInView_51a02b68 = 1
SET
  @AutoUpdateCategory_51a02b68 = 1
SET
  @AutoUpdateDisplayName_51a02b68 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_51a02b68 = 1
SET
  @Encrypt_51a02b68 = 0
SET
  @AllowDecryptInAPI_51a02b68 = 0
SET
  @SendEncryptedValue_51a02b68 = 0
SET
  @IsSoftPrimaryKey_51a02b68 = 0
SET
  @IsSoftForeignKey_51a02b68 = 0
SET
  @JSONTypeIsArray_51a02b68 = 0
SET
  @UserSearchPredicateAPI_51a02b68 = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_51a02b68 = 1
SET
  @AutoUpdateFullTextSearch_51a02b68 = 1
SET
  @AutoUpdateExtendedType_51a02b68 = 1
SET
  @IsComputed_51a02b68 = 0
SET
  @ID_51a02b68 = '0D7D2672-D189-402E-A84E-249EC5ABBD3E' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_51a02b68,
  @Description = @Description_51a02b68,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_51a02b68,
  @IsPrimaryKey = @IsPrimaryKey_51a02b68,
  @IsUnique = @IsUnique_51a02b68,
  @Category = @Category_51a02b68,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_51a02b68,
  @ExtendedType = @ExtendedType_51a02b68,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_51a02b68,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_51a02b68,
  @ViewCellTemplate = @ViewCellTemplate_51a02b68,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_51a02b68,
  @AllowUpdateAPI = @AllowUpdateAPI_51a02b68,
  @AllowUpdateInView = @AllowUpdateInView_51a02b68,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_51a02b68,
  @FullTextSearchEnabled = @FullTextSearchEnabled_51a02b68,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_51a02b68,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_51a02b68,
  @GeneratedFormSection = @GeneratedFormSection_51a02b68,
  @IsNameField = @IsNameField_51a02b68,
  @RelatedEntityID = @RelatedEntityID_51a02b68,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_51a02b68,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_51a02b68,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_51a02b68,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_51a02b68,
  @EntityIDFieldName = @EntityIDFieldName_51a02b68,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_51a02b68,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_51a02b68,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_51a02b68,
  @Status = @Status_51a02b68,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_51a02b68,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_51a02b68,
  @AutoUpdateCategory = @AutoUpdateCategory_51a02b68,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_51a02b68,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_51a02b68,
  @Encrypt = @Encrypt_51a02b68,
  @EncryptionKeyID = @EncryptionKeyID_51a02b68,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_51a02b68,
  @SendEncryptedValue = @SendEncryptedValue_51a02b68,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_51a02b68,
  @IsSoftForeignKey = @IsSoftForeignKey_51a02b68,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_51a02b68,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_51a02b68,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_51a02b68,
  @JSONTypeDefinition = @JSONTypeDefinition_51a02b68,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_51a02b68,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_51a02b68,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_51a02b68,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_51a02b68,
  @IsComputed = @IsComputed_51a02b68,
  @EmbeddedRecord = @EmbeddedRecord_51a02b68,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_51a02b68,
  @Configuration_Clear = 1,
  @ID = @ID_51a02b68;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_4a4390a8 NVARCHAR(255),
@Description_4a4390a8 NVARCHAR(MAX),
@AutoUpdateDescription_4a4390a8 BIT,
@IsPrimaryKey_4a4390a8 BIT,
@IsUnique_4a4390a8 BIT,
@Category_4a4390a8 NVARCHAR(255),
@ValueListType_4a4390a8 NVARCHAR(20),
@ExtendedType_4a4390a8 NVARCHAR(50),
@CodeType_4a4390a8 NVARCHAR(50),
@DefaultInView_4a4390a8 BIT,
@ViewCellTemplate_4a4390a8 NVARCHAR(MAX),
@DefaultColumnWidth_4a4390a8 INT,
@AllowUpdateAPI_4a4390a8 BIT,
@AllowUpdateInView_4a4390a8 BIT,
@IncludeInUserSearchAPI_4a4390a8 BIT,
@FullTextSearchEnabled_4a4390a8 BIT,
@UserSearchParamFormatAPI_4a4390a8 NVARCHAR(500),
@IncludeInGeneratedForm_4a4390a8 BIT,
@GeneratedFormSection_4a4390a8 NVARCHAR(10),
@IsNameField_4a4390a8 BIT,
@RelatedEntityID_4a4390a8 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_4a4390a8 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_4a4390a8 BIT,
@RelatedEntityNameFieldMap_4a4390a8 NVARCHAR(255),
@RelatedEntityDisplayType_4a4390a8 NVARCHAR(20),
@EntityIDFieldName_4a4390a8 NVARCHAR(100),
@ScopeDefault_4a4390a8 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_4a4390a8 BIT,
@ValuesToPackWithSchema_4a4390a8 NVARCHAR(10),
@Status_4a4390a8 NVARCHAR(25),
@AutoUpdateIsNameField_4a4390a8 BIT,
@AutoUpdateDefaultInView_4a4390a8 BIT,
@AutoUpdateCategory_4a4390a8 BIT,
@AutoUpdateDisplayName_4a4390a8 BIT,
@AutoUpdateIncludeInUserSearchAPI_4a4390a8 BIT,
@Encrypt_4a4390a8 BIT,
@EncryptionKeyID_4a4390a8 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_4a4390a8 BIT,
@SendEncryptedValue_4a4390a8 BIT,
@IsSoftPrimaryKey_4a4390a8 BIT,
@IsSoftForeignKey_4a4390a8 BIT,
@RelatedEntityJoinFields_4a4390a8 NVARCHAR(MAX),
@JSONType_4a4390a8 NVARCHAR(255),
@JSONTypeIsArray_4a4390a8 BIT,
@JSONTypeDefinition_4a4390a8 NVARCHAR(MAX),
@UserSearchPredicateAPI_4a4390a8 NVARCHAR(20),
@AutoUpdateUserSearchPredicate_4a4390a8 BIT,
@AutoUpdateFullTextSearch_4a4390a8 BIT,
@AutoUpdateExtendedType_4a4390a8 BIT,
@IsComputed_4a4390a8 BIT,
@EmbeddedRecord_4a4390a8 NVARCHAR(MAX),
@Configuration_4a4390a8 NVARCHAR(MAX),
@ID_4a4390a8 UNIQUEIDENTIFIER
SET
  @DisplayName_4a4390a8 = N'Amount'
SET
  @Description_4a4390a8 = N'The deal value. A CACHED ANSWER returned by Orders.PreviewOrder for this deal''s line set — NOT computed here. For a simple (header-only) deal it is hand-entered and AmountIsComputed is 0. Never sum the order''s lines into this column; sales does no arithmetic.'
SET
  @AutoUpdateDescription_4a4390a8 = 1
SET
  @IsPrimaryKey_4a4390a8 = 0
SET
  @IsUnique_4a4390a8 = 0
SET
  @ValueListType_4a4390a8 = N'None'
SET
  @DefaultInView_4a4390a8 = 1
SET
  @DefaultColumnWidth_4a4390a8 = 150
SET
  @AllowUpdateAPI_4a4390a8 = 1
SET
  @AllowUpdateInView_4a4390a8 = 1
SET
  @IncludeInUserSearchAPI_4a4390a8 = 0
SET
  @FullTextSearchEnabled_4a4390a8 = 0
SET
  @IncludeInGeneratedForm_4a4390a8 = 1
SET
  @GeneratedFormSection_4a4390a8 = N'Details'
SET
  @IsNameField_4a4390a8 = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_4a4390a8 = 0
SET
  @RelatedEntityDisplayType_4a4390a8 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_4a4390a8 = 1
SET
  @ValuesToPackWithSchema_4a4390a8 = N'Auto'
SET
  @Status_4a4390a8 = N'Active'
SET
  @AutoUpdateIsNameField_4a4390a8 = 1
SET
  @AutoUpdateDefaultInView_4a4390a8 = 1
SET
  @AutoUpdateCategory_4a4390a8 = 1
SET
  @AutoUpdateDisplayName_4a4390a8 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_4a4390a8 = 1
SET
  @Encrypt_4a4390a8 = 0
SET
  @AllowDecryptInAPI_4a4390a8 = 0
SET
  @SendEncryptedValue_4a4390a8 = 0
SET
  @IsSoftPrimaryKey_4a4390a8 = 0
SET
  @IsSoftForeignKey_4a4390a8 = 0
SET
  @JSONTypeIsArray_4a4390a8 = 0
SET
  @UserSearchPredicateAPI_4a4390a8 = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_4a4390a8 = 1
SET
  @AutoUpdateFullTextSearch_4a4390a8 = 1
SET
  @AutoUpdateExtendedType_4a4390a8 = 1
SET
  @IsComputed_4a4390a8 = 0
SET
  @ID_4a4390a8 = '440893BB-B492-4D23-B250-EE48A590182F' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_4a4390a8,
  @Description = @Description_4a4390a8,
  @AutoUpdateDescription = @AutoUpdateDescription_4a4390a8,
  @IsPrimaryKey = @IsPrimaryKey_4a4390a8,
  @IsUnique = @IsUnique_4a4390a8,
  @Category = @Category_4a4390a8,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_4a4390a8,
  @ExtendedType = @ExtendedType_4a4390a8,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_4a4390a8,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_4a4390a8,
  @ViewCellTemplate = @ViewCellTemplate_4a4390a8,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_4a4390a8,
  @AllowUpdateAPI = @AllowUpdateAPI_4a4390a8,
  @AllowUpdateInView = @AllowUpdateInView_4a4390a8,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_4a4390a8,
  @FullTextSearchEnabled = @FullTextSearchEnabled_4a4390a8,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_4a4390a8,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_4a4390a8,
  @GeneratedFormSection = @GeneratedFormSection_4a4390a8,
  @IsNameField = @IsNameField_4a4390a8,
  @RelatedEntityID = @RelatedEntityID_4a4390a8,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_4a4390a8,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_4a4390a8,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_4a4390a8,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_4a4390a8,
  @EntityIDFieldName = @EntityIDFieldName_4a4390a8,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_4a4390a8,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_4a4390a8,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_4a4390a8,
  @Status = @Status_4a4390a8,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_4a4390a8,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_4a4390a8,
  @AutoUpdateCategory = @AutoUpdateCategory_4a4390a8,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_4a4390a8,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_4a4390a8,
  @Encrypt = @Encrypt_4a4390a8,
  @EncryptionKeyID = @EncryptionKeyID_4a4390a8,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_4a4390a8,
  @SendEncryptedValue = @SendEncryptedValue_4a4390a8,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_4a4390a8,
  @IsSoftForeignKey = @IsSoftForeignKey_4a4390a8,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_4a4390a8,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_4a4390a8,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_4a4390a8,
  @JSONTypeDefinition = @JSONTypeDefinition_4a4390a8,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_4a4390a8,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_4a4390a8,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_4a4390a8,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_4a4390a8,
  @IsComputed = @IsComputed_4a4390a8,
  @EmbeddedRecord = @EmbeddedRecord_4a4390a8,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_4a4390a8,
  @Configuration_Clear = 1,
  @ID = @ID_4a4390a8;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_606e0cc1 NVARCHAR(255),
@Description_606e0cc1 NVARCHAR(MAX),
@AutoUpdateDescription_606e0cc1 BIT,
@IsPrimaryKey_606e0cc1 BIT,
@IsUnique_606e0cc1 BIT,
@Category_606e0cc1 NVARCHAR(255),
@ValueListType_606e0cc1 NVARCHAR(20),
@ExtendedType_606e0cc1 NVARCHAR(50),
@CodeType_606e0cc1 NVARCHAR(50),
@DefaultInView_606e0cc1 BIT,
@ViewCellTemplate_606e0cc1 NVARCHAR(MAX),
@DefaultColumnWidth_606e0cc1 INT,
@AllowUpdateAPI_606e0cc1 BIT,
@AllowUpdateInView_606e0cc1 BIT,
@IncludeInUserSearchAPI_606e0cc1 BIT,
@FullTextSearchEnabled_606e0cc1 BIT,
@UserSearchParamFormatAPI_606e0cc1 NVARCHAR(500),
@IncludeInGeneratedForm_606e0cc1 BIT,
@GeneratedFormSection_606e0cc1 NVARCHAR(10),
@IsNameField_606e0cc1 BIT,
@RelatedEntityID_606e0cc1 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_606e0cc1 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_606e0cc1 BIT,
@RelatedEntityNameFieldMap_606e0cc1 NVARCHAR(255),
@RelatedEntityDisplayType_606e0cc1 NVARCHAR(20),
@EntityIDFieldName_606e0cc1 NVARCHAR(100),
@ScopeDefault_606e0cc1 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_606e0cc1 BIT,
@ValuesToPackWithSchema_606e0cc1 NVARCHAR(10),
@Status_606e0cc1 NVARCHAR(25),
@AutoUpdateIsNameField_606e0cc1 BIT,
@AutoUpdateDefaultInView_606e0cc1 BIT,
@AutoUpdateCategory_606e0cc1 BIT,
@AutoUpdateDisplayName_606e0cc1 BIT,
@AutoUpdateIncludeInUserSearchAPI_606e0cc1 BIT,
@Encrypt_606e0cc1 BIT,
@EncryptionKeyID_606e0cc1 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_606e0cc1 BIT,
@SendEncryptedValue_606e0cc1 BIT,
@IsSoftPrimaryKey_606e0cc1 BIT,
@IsSoftForeignKey_606e0cc1 BIT,
@RelatedEntityJoinFields_606e0cc1 NVARCHAR(MAX),
@JSONType_606e0cc1 NVARCHAR(255),
@JSONTypeIsArray_606e0cc1 BIT,
@JSONTypeDefinition_606e0cc1 NVARCHAR(MAX),
@UserSearchPredicateAPI_606e0cc1 NVARCHAR(20),
@AutoUpdateUserSearchPredicate_606e0cc1 BIT,
@AutoUpdateFullTextSearch_606e0cc1 BIT,
@AutoUpdateExtendedType_606e0cc1 BIT,
@IsComputed_606e0cc1 BIT,
@EmbeddedRecord_606e0cc1 NVARCHAR(MAX),
@Configuration_606e0cc1 NVARCHAR(MAX),
@ID_606e0cc1 UNIQUEIDENTIFIER
SET
  @DisplayName_606e0cc1 = N'Probability'
SET
  @AutoUpdateDescription_606e0cc1 = 1
SET
  @IsPrimaryKey_606e0cc1 = 0
SET
  @IsUnique_606e0cc1 = 0
SET
  @ValueListType_606e0cc1 = N'None'
SET
  @DefaultInView_606e0cc1 = 1
SET
  @DefaultColumnWidth_606e0cc1 = 150
SET
  @AllowUpdateAPI_606e0cc1 = 1
SET
  @AllowUpdateInView_606e0cc1 = 1
SET
  @IncludeInUserSearchAPI_606e0cc1 = 0
SET
  @FullTextSearchEnabled_606e0cc1 = 0
SET
  @IncludeInGeneratedForm_606e0cc1 = 1
SET
  @GeneratedFormSection_606e0cc1 = N'Details'
SET
  @IsNameField_606e0cc1 = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_606e0cc1 = 0
SET
  @RelatedEntityDisplayType_606e0cc1 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_606e0cc1 = 1
SET
  @ValuesToPackWithSchema_606e0cc1 = N'Auto'
SET
  @Status_606e0cc1 = N'Active'
SET
  @AutoUpdateIsNameField_606e0cc1 = 1
SET
  @AutoUpdateDefaultInView_606e0cc1 = 1
SET
  @AutoUpdateCategory_606e0cc1 = 1
SET
  @AutoUpdateDisplayName_606e0cc1 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_606e0cc1 = 1
SET
  @Encrypt_606e0cc1 = 0
SET
  @AllowDecryptInAPI_606e0cc1 = 0
SET
  @SendEncryptedValue_606e0cc1 = 0
SET
  @IsSoftPrimaryKey_606e0cc1 = 0
SET
  @IsSoftForeignKey_606e0cc1 = 0
SET
  @JSONTypeIsArray_606e0cc1 = 0
SET
  @UserSearchPredicateAPI_606e0cc1 = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_606e0cc1 = 1
SET
  @AutoUpdateFullTextSearch_606e0cc1 = 1
SET
  @AutoUpdateExtendedType_606e0cc1 = 1
SET
  @IsComputed_606e0cc1 = 0
SET
  @ID_606e0cc1 = 'C0D9A787-0AF2-4158-B5ED-E2BCEC3C84CB' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_606e0cc1,
  @Description = @Description_606e0cc1,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_606e0cc1,
  @IsPrimaryKey = @IsPrimaryKey_606e0cc1,
  @IsUnique = @IsUnique_606e0cc1,
  @Category = @Category_606e0cc1,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_606e0cc1,
  @ExtendedType = @ExtendedType_606e0cc1,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_606e0cc1,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_606e0cc1,
  @ViewCellTemplate = @ViewCellTemplate_606e0cc1,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_606e0cc1,
  @AllowUpdateAPI = @AllowUpdateAPI_606e0cc1,
  @AllowUpdateInView = @AllowUpdateInView_606e0cc1,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_606e0cc1,
  @FullTextSearchEnabled = @FullTextSearchEnabled_606e0cc1,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_606e0cc1,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_606e0cc1,
  @GeneratedFormSection = @GeneratedFormSection_606e0cc1,
  @IsNameField = @IsNameField_606e0cc1,
  @RelatedEntityID = @RelatedEntityID_606e0cc1,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_606e0cc1,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_606e0cc1,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_606e0cc1,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_606e0cc1,
  @EntityIDFieldName = @EntityIDFieldName_606e0cc1,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_606e0cc1,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_606e0cc1,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_606e0cc1,
  @Status = @Status_606e0cc1,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_606e0cc1,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_606e0cc1,
  @AutoUpdateCategory = @AutoUpdateCategory_606e0cc1,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_606e0cc1,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_606e0cc1,
  @Encrypt = @Encrypt_606e0cc1,
  @EncryptionKeyID = @EncryptionKeyID_606e0cc1,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_606e0cc1,
  @SendEncryptedValue = @SendEncryptedValue_606e0cc1,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_606e0cc1,
  @IsSoftForeignKey = @IsSoftForeignKey_606e0cc1,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_606e0cc1,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_606e0cc1,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_606e0cc1,
  @JSONTypeDefinition = @JSONTypeDefinition_606e0cc1,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_606e0cc1,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_606e0cc1,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_606e0cc1,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_606e0cc1,
  @IsComputed = @IsComputed_606e0cc1,
  @EmbeddedRecord = @EmbeddedRecord_606e0cc1,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_606e0cc1,
  @Configuration_Clear = 1,
  @ID = @ID_606e0cc1;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_66764eb3 NVARCHAR(255),
@Description_66764eb3 NVARCHAR(MAX),
@AutoUpdateDescription_66764eb3 BIT,
@IsPrimaryKey_66764eb3 BIT,
@IsUnique_66764eb3 BIT,
@Category_66764eb3 NVARCHAR(255),
@ValueListType_66764eb3 NVARCHAR(20),
@ExtendedType_66764eb3 NVARCHAR(50),
@CodeType_66764eb3 NVARCHAR(50),
@DefaultInView_66764eb3 BIT,
@ViewCellTemplate_66764eb3 NVARCHAR(MAX),
@DefaultColumnWidth_66764eb3 INT,
@AllowUpdateAPI_66764eb3 BIT,
@AllowUpdateInView_66764eb3 BIT,
@IncludeInUserSearchAPI_66764eb3 BIT,
@FullTextSearchEnabled_66764eb3 BIT,
@UserSearchParamFormatAPI_66764eb3 NVARCHAR(500),
@IncludeInGeneratedForm_66764eb3 BIT,
@GeneratedFormSection_66764eb3 NVARCHAR(10),
@IsNameField_66764eb3 BIT,
@RelatedEntityID_66764eb3 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_66764eb3 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_66764eb3 BIT,
@RelatedEntityNameFieldMap_66764eb3 NVARCHAR(255),
@RelatedEntityDisplayType_66764eb3 NVARCHAR(20),
@EntityIDFieldName_66764eb3 NVARCHAR(100),
@ScopeDefault_66764eb3 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_66764eb3 BIT,
@ValuesToPackWithSchema_66764eb3 NVARCHAR(10),
@Status_66764eb3 NVARCHAR(25),
@AutoUpdateIsNameField_66764eb3 BIT,
@AutoUpdateDefaultInView_66764eb3 BIT,
@AutoUpdateCategory_66764eb3 BIT,
@AutoUpdateDisplayName_66764eb3 BIT,
@AutoUpdateIncludeInUserSearchAPI_66764eb3 BIT,
@Encrypt_66764eb3 BIT,
@EncryptionKeyID_66764eb3 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_66764eb3 BIT,
@SendEncryptedValue_66764eb3 BIT,
@IsSoftPrimaryKey_66764eb3 BIT,
@IsSoftForeignKey_66764eb3 BIT,
@RelatedEntityJoinFields_66764eb3 NVARCHAR(MAX),
@JSONType_66764eb3 NVARCHAR(255),
@JSONTypeIsArray_66764eb3 BIT,
@JSONTypeDefinition_66764eb3 NVARCHAR(MAX),
@UserSearchPredicateAPI_66764eb3 NVARCHAR(20),
@AutoUpdateUserSearchPredicate_66764eb3 BIT,
@AutoUpdateFullTextSearch_66764eb3 BIT,
@AutoUpdateExtendedType_66764eb3 BIT,
@IsComputed_66764eb3 BIT,
@EmbeddedRecord_66764eb3 NVARCHAR(MAX),
@Configuration_66764eb3 NVARCHAR(MAX),
@ID_66764eb3 UNIQUEIDENTIFIER
SET
  @DisplayName_66764eb3 = N'Expected Close Date'
SET
  @AutoUpdateDescription_66764eb3 = 1
SET
  @IsPrimaryKey_66764eb3 = 0
SET
  @IsUnique_66764eb3 = 0
SET
  @ValueListType_66764eb3 = N'None'
SET
  @DefaultInView_66764eb3 = 1
SET
  @DefaultColumnWidth_66764eb3 = 150
SET
  @AllowUpdateAPI_66764eb3 = 1
SET
  @AllowUpdateInView_66764eb3 = 1
SET
  @IncludeInUserSearchAPI_66764eb3 = 0
SET
  @FullTextSearchEnabled_66764eb3 = 0
SET
  @IncludeInGeneratedForm_66764eb3 = 1
SET
  @GeneratedFormSection_66764eb3 = N'Details'
SET
  @IsNameField_66764eb3 = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_66764eb3 = 0
SET
  @RelatedEntityDisplayType_66764eb3 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_66764eb3 = 1
SET
  @ValuesToPackWithSchema_66764eb3 = N'Auto'
SET
  @Status_66764eb3 = N'Active'
SET
  @AutoUpdateIsNameField_66764eb3 = 1
SET
  @AutoUpdateDefaultInView_66764eb3 = 1
SET
  @AutoUpdateCategory_66764eb3 = 1
SET
  @AutoUpdateDisplayName_66764eb3 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_66764eb3 = 1
SET
  @Encrypt_66764eb3 = 0
SET
  @AllowDecryptInAPI_66764eb3 = 0
SET
  @SendEncryptedValue_66764eb3 = 0
SET
  @IsSoftPrimaryKey_66764eb3 = 0
SET
  @IsSoftForeignKey_66764eb3 = 0
SET
  @JSONTypeIsArray_66764eb3 = 0
SET
  @UserSearchPredicateAPI_66764eb3 = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_66764eb3 = 1
SET
  @AutoUpdateFullTextSearch_66764eb3 = 1
SET
  @AutoUpdateExtendedType_66764eb3 = 1
SET
  @IsComputed_66764eb3 = 0
SET
  @ID_66764eb3 = '6AC23D15-33D1-4618-B582-01EC9F40655B' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_66764eb3,
  @Description = @Description_66764eb3,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_66764eb3,
  @IsPrimaryKey = @IsPrimaryKey_66764eb3,
  @IsUnique = @IsUnique_66764eb3,
  @Category = @Category_66764eb3,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_66764eb3,
  @ExtendedType = @ExtendedType_66764eb3,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_66764eb3,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_66764eb3,
  @ViewCellTemplate = @ViewCellTemplate_66764eb3,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_66764eb3,
  @AllowUpdateAPI = @AllowUpdateAPI_66764eb3,
  @AllowUpdateInView = @AllowUpdateInView_66764eb3,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_66764eb3,
  @FullTextSearchEnabled = @FullTextSearchEnabled_66764eb3,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_66764eb3,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_66764eb3,
  @GeneratedFormSection = @GeneratedFormSection_66764eb3,
  @IsNameField = @IsNameField_66764eb3,
  @RelatedEntityID = @RelatedEntityID_66764eb3,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_66764eb3,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_66764eb3,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_66764eb3,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_66764eb3,
  @EntityIDFieldName = @EntityIDFieldName_66764eb3,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_66764eb3,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_66764eb3,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_66764eb3,
  @Status = @Status_66764eb3,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_66764eb3,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_66764eb3,
  @AutoUpdateCategory = @AutoUpdateCategory_66764eb3,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_66764eb3,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_66764eb3,
  @Encrypt = @Encrypt_66764eb3,
  @EncryptionKeyID = @EncryptionKeyID_66764eb3,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_66764eb3,
  @SendEncryptedValue = @SendEncryptedValue_66764eb3,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_66764eb3,
  @IsSoftForeignKey = @IsSoftForeignKey_66764eb3,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_66764eb3,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_66764eb3,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_66764eb3,
  @JSONTypeDefinition = @JSONTypeDefinition_66764eb3,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_66764eb3,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_66764eb3,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_66764eb3,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_66764eb3,
  @IsComputed = @IsComputed_66764eb3,
  @EmbeddedRecord = @EmbeddedRecord_66764eb3,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_66764eb3,
  @Configuration_Clear = 1,
  @ID = @ID_66764eb3;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_11912065 NVARCHAR(255),
@Description_11912065 NVARCHAR(MAX),
@AutoUpdateDescription_11912065 BIT,
@IsPrimaryKey_11912065 BIT,
@IsUnique_11912065 BIT,
@Category_11912065 NVARCHAR(255),
@ValueListType_11912065 NVARCHAR(20),
@ExtendedType_11912065 NVARCHAR(50),
@CodeType_11912065 NVARCHAR(50),
@DefaultInView_11912065 BIT,
@ViewCellTemplate_11912065 NVARCHAR(MAX),
@DefaultColumnWidth_11912065 INT,
@AllowUpdateAPI_11912065 BIT,
@AllowUpdateInView_11912065 BIT,
@IncludeInUserSearchAPI_11912065 BIT,
@FullTextSearchEnabled_11912065 BIT,
@UserSearchParamFormatAPI_11912065 NVARCHAR(500),
@IncludeInGeneratedForm_11912065 BIT,
@GeneratedFormSection_11912065 NVARCHAR(10),
@IsNameField_11912065 BIT,
@RelatedEntityID_11912065 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_11912065 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_11912065 BIT,
@RelatedEntityNameFieldMap_11912065 NVARCHAR(255),
@RelatedEntityDisplayType_11912065 NVARCHAR(20),
@EntityIDFieldName_11912065 NVARCHAR(100),
@ScopeDefault_11912065 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_11912065 BIT,
@ValuesToPackWithSchema_11912065 NVARCHAR(10),
@Status_11912065 NVARCHAR(25),
@AutoUpdateIsNameField_11912065 BIT,
@AutoUpdateDefaultInView_11912065 BIT,
@AutoUpdateCategory_11912065 BIT,
@AutoUpdateDisplayName_11912065 BIT,
@AutoUpdateIncludeInUserSearchAPI_11912065 BIT,
@Encrypt_11912065 BIT,
@EncryptionKeyID_11912065 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_11912065 BIT,
@SendEncryptedValue_11912065 BIT,
@IsSoftPrimaryKey_11912065 BIT,
@IsSoftForeignKey_11912065 BIT,
@RelatedEntityJoinFields_11912065 NVARCHAR(MAX),
@JSONType_11912065 NVARCHAR(255),
@JSONTypeIsArray_11912065 BIT,
@JSONTypeDefinition_11912065 NVARCHAR(MAX),
@UserSearchPredicateAPI_11912065 NVARCHAR(20),
@AutoUpdateUserSearchPredicate_11912065 BIT,
@AutoUpdateFullTextSearch_11912065 BIT,
@AutoUpdateExtendedType_11912065 BIT,
@IsComputed_11912065 BIT,
@EmbeddedRecord_11912065 NVARCHAR(MAX),
@Configuration_11912065 NVARCHAR(MAX),
@ID_11912065 UNIQUEIDENTIFIER
SET
  @DisplayName_11912065 = N'Owner Employee'
SET
  @AutoUpdateDescription_11912065 = 1
SET
  @IsPrimaryKey_11912065 = 0
SET
  @IsUnique_11912065 = 0
SET
  @ValueListType_11912065 = N'None'
SET
  @DefaultInView_11912065 = 1
SET
  @DefaultColumnWidth_11912065 = 150
SET
  @AllowUpdateAPI_11912065 = 0
SET
  @AllowUpdateInView_11912065 = 1
SET
  @IncludeInUserSearchAPI_11912065 = 0
SET
  @FullTextSearchEnabled_11912065 = 0
SET
  @IncludeInGeneratedForm_11912065 = 1
SET
  @GeneratedFormSection_11912065 = N'Details'
SET
  @IsNameField_11912065 = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_11912065 = 0
SET
  @RelatedEntityDisplayType_11912065 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_11912065 = 1
SET
  @ValuesToPackWithSchema_11912065 = N'Auto'
SET
  @Status_11912065 = N'Active'
SET
  @AutoUpdateIsNameField_11912065 = 1
SET
  @AutoUpdateDefaultInView_11912065 = 1
SET
  @AutoUpdateCategory_11912065 = 1
SET
  @AutoUpdateDisplayName_11912065 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_11912065 = 1
SET
  @Encrypt_11912065 = 0
SET
  @AllowDecryptInAPI_11912065 = 0
SET
  @SendEncryptedValue_11912065 = 0
SET
  @IsSoftPrimaryKey_11912065 = 0
SET
  @IsSoftForeignKey_11912065 = 0
SET
  @JSONTypeIsArray_11912065 = 0
SET
  @UserSearchPredicateAPI_11912065 = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_11912065 = 1
SET
  @AutoUpdateFullTextSearch_11912065 = 1
SET
  @AutoUpdateExtendedType_11912065 = 1
SET
  @IsComputed_11912065 = 0
SET
  @ID_11912065 = '3442E4F5-F87C-4993-9AB3-38D7FBBECF88' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_11912065,
  @Description = @Description_11912065,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_11912065,
  @IsPrimaryKey = @IsPrimaryKey_11912065,
  @IsUnique = @IsUnique_11912065,
  @Category = @Category_11912065,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_11912065,
  @ExtendedType = @ExtendedType_11912065,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_11912065,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_11912065,
  @ViewCellTemplate = @ViewCellTemplate_11912065,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_11912065,
  @AllowUpdateAPI = @AllowUpdateAPI_11912065,
  @AllowUpdateInView = @AllowUpdateInView_11912065,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_11912065,
  @FullTextSearchEnabled = @FullTextSearchEnabled_11912065,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_11912065,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_11912065,
  @GeneratedFormSection = @GeneratedFormSection_11912065,
  @IsNameField = @IsNameField_11912065,
  @RelatedEntityID = @RelatedEntityID_11912065,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_11912065,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_11912065,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_11912065,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_11912065,
  @EntityIDFieldName = @EntityIDFieldName_11912065,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_11912065,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_11912065,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_11912065,
  @Status = @Status_11912065,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_11912065,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_11912065,
  @AutoUpdateCategory = @AutoUpdateCategory_11912065,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_11912065,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_11912065,
  @Encrypt = @Encrypt_11912065,
  @EncryptionKeyID = @EncryptionKeyID_11912065,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_11912065,
  @SendEncryptedValue = @SendEncryptedValue_11912065,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_11912065,
  @IsSoftForeignKey = @IsSoftForeignKey_11912065,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_11912065,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_11912065,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_11912065,
  @JSONTypeDefinition = @JSONTypeDefinition_11912065,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_11912065,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_11912065,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_11912065,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_11912065,
  @IsComputed = @IsComputed_11912065,
  @EmbeddedRecord = @EmbeddedRecord_11912065,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_11912065,
  @Configuration_Clear = 1,
  @ID = @ID_11912065;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_92bac19c NVARCHAR(255),
@Description_92bac19c NVARCHAR(MAX),
@AutoUpdateDescription_92bac19c BIT,
@IsPrimaryKey_92bac19c BIT,
@IsUnique_92bac19c BIT,
@Category_92bac19c NVARCHAR(255),
@ValueListType_92bac19c NVARCHAR(20),
@ExtendedType_92bac19c NVARCHAR(50),
@CodeType_92bac19c NVARCHAR(50),
@DefaultInView_92bac19c BIT,
@ViewCellTemplate_92bac19c NVARCHAR(MAX),
@DefaultColumnWidth_92bac19c INT,
@AllowUpdateAPI_92bac19c BIT,
@AllowUpdateInView_92bac19c BIT,
@IncludeInUserSearchAPI_92bac19c BIT,
@FullTextSearchEnabled_92bac19c BIT,
@UserSearchParamFormatAPI_92bac19c NVARCHAR(500),
@IncludeInGeneratedForm_92bac19c BIT,
@GeneratedFormSection_92bac19c NVARCHAR(10),
@IsNameField_92bac19c BIT,
@RelatedEntityID_92bac19c UNIQUEIDENTIFIER,
@RelatedEntityFieldName_92bac19c NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_92bac19c BIT,
@RelatedEntityNameFieldMap_92bac19c NVARCHAR(255),
@RelatedEntityDisplayType_92bac19c NVARCHAR(20),
@EntityIDFieldName_92bac19c NVARCHAR(100),
@ScopeDefault_92bac19c NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_92bac19c BIT,
@ValuesToPackWithSchema_92bac19c NVARCHAR(10),
@Status_92bac19c NVARCHAR(25),
@AutoUpdateIsNameField_92bac19c BIT,
@AutoUpdateDefaultInView_92bac19c BIT,
@AutoUpdateCategory_92bac19c BIT,
@AutoUpdateDisplayName_92bac19c BIT,
@AutoUpdateIncludeInUserSearchAPI_92bac19c BIT,
@Encrypt_92bac19c BIT,
@EncryptionKeyID_92bac19c UNIQUEIDENTIFIER,
@AllowDecryptInAPI_92bac19c BIT,
@SendEncryptedValue_92bac19c BIT,
@IsSoftPrimaryKey_92bac19c BIT,
@IsSoftForeignKey_92bac19c BIT,
@RelatedEntityJoinFields_92bac19c NVARCHAR(MAX),
@JSONType_92bac19c NVARCHAR(255),
@JSONTypeIsArray_92bac19c BIT,
@JSONTypeDefinition_92bac19c NVARCHAR(MAX),
@UserSearchPredicateAPI_92bac19c NVARCHAR(20),
@AutoUpdateUserSearchPredicate_92bac19c BIT,
@AutoUpdateFullTextSearch_92bac19c BIT,
@AutoUpdateExtendedType_92bac19c BIT,
@IsComputed_92bac19c BIT,
@EmbeddedRecord_92bac19c NVARCHAR(MAX),
@Configuration_92bac19c NVARCHAR(MAX),
@ID_92bac19c UNIQUEIDENTIFIER
SET
  @DisplayName_92bac19c = N'Forecast Category Type'
SET
  @AutoUpdateDescription_92bac19c = 1
SET
  @IsPrimaryKey_92bac19c = 0
SET
  @IsUnique_92bac19c = 0
SET
  @ValueListType_92bac19c = N'None'
SET
  @DefaultInView_92bac19c = 1
SET
  @DefaultColumnWidth_92bac19c = 150
SET
  @AllowUpdateAPI_92bac19c = 0
SET
  @AllowUpdateInView_92bac19c = 1
SET
  @IncludeInUserSearchAPI_92bac19c = 0
SET
  @FullTextSearchEnabled_92bac19c = 0
SET
  @IncludeInGeneratedForm_92bac19c = 1
SET
  @GeneratedFormSection_92bac19c = N'Details'
SET
  @IsNameField_92bac19c = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_92bac19c = 0
SET
  @RelatedEntityDisplayType_92bac19c = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_92bac19c = 1
SET
  @ValuesToPackWithSchema_92bac19c = N'Auto'
SET
  @Status_92bac19c = N'Active'
SET
  @AutoUpdateIsNameField_92bac19c = 1
SET
  @AutoUpdateDefaultInView_92bac19c = 1
SET
  @AutoUpdateCategory_92bac19c = 1
SET
  @AutoUpdateDisplayName_92bac19c = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_92bac19c = 1
SET
  @Encrypt_92bac19c = 0
SET
  @AllowDecryptInAPI_92bac19c = 0
SET
  @SendEncryptedValue_92bac19c = 0
SET
  @IsSoftPrimaryKey_92bac19c = 0
SET
  @IsSoftForeignKey_92bac19c = 0
SET
  @JSONTypeIsArray_92bac19c = 0
SET
  @UserSearchPredicateAPI_92bac19c = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_92bac19c = 1
SET
  @AutoUpdateFullTextSearch_92bac19c = 1
SET
  @AutoUpdateExtendedType_92bac19c = 1
SET
  @IsComputed_92bac19c = 0
SET
  @ID_92bac19c = '646E4D6C-2A09-49E4-BBF5-E18A4D944DD2' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_92bac19c,
  @Description = @Description_92bac19c,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_92bac19c,
  @IsPrimaryKey = @IsPrimaryKey_92bac19c,
  @IsUnique = @IsUnique_92bac19c,
  @Category = @Category_92bac19c,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_92bac19c,
  @ExtendedType = @ExtendedType_92bac19c,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_92bac19c,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_92bac19c,
  @ViewCellTemplate = @ViewCellTemplate_92bac19c,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_92bac19c,
  @AllowUpdateAPI = @AllowUpdateAPI_92bac19c,
  @AllowUpdateInView = @AllowUpdateInView_92bac19c,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_92bac19c,
  @FullTextSearchEnabled = @FullTextSearchEnabled_92bac19c,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_92bac19c,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_92bac19c,
  @GeneratedFormSection = @GeneratedFormSection_92bac19c,
  @IsNameField = @IsNameField_92bac19c,
  @RelatedEntityID = @RelatedEntityID_92bac19c,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_92bac19c,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_92bac19c,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_92bac19c,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_92bac19c,
  @EntityIDFieldName = @EntityIDFieldName_92bac19c,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_92bac19c,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_92bac19c,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_92bac19c,
  @Status = @Status_92bac19c,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_92bac19c,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_92bac19c,
  @AutoUpdateCategory = @AutoUpdateCategory_92bac19c,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_92bac19c,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_92bac19c,
  @Encrypt = @Encrypt_92bac19c,
  @EncryptionKeyID = @EncryptionKeyID_92bac19c,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_92bac19c,
  @SendEncryptedValue = @SendEncryptedValue_92bac19c,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_92bac19c,
  @IsSoftForeignKey = @IsSoftForeignKey_92bac19c,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_92bac19c,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_92bac19c,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_92bac19c,
  @JSONTypeDefinition = @JSONTypeDefinition_92bac19c,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_92bac19c,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_92bac19c,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_92bac19c,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_92bac19c,
  @IsComputed = @IsComputed_92bac19c,
  @EmbeddedRecord = @EmbeddedRecord_92bac19c,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_92bac19c,
  @Configuration_Clear = 1,
  @ID = @ID_92bac19c;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_5621e848 NVARCHAR(255),
@Description_5621e848 NVARCHAR(MAX),
@AutoUpdateDescription_5621e848 BIT,
@IsPrimaryKey_5621e848 BIT,
@IsUnique_5621e848 BIT,
@Category_5621e848 NVARCHAR(255),
@ValueListType_5621e848 NVARCHAR(20),
@ExtendedType_5621e848 NVARCHAR(50),
@CodeType_5621e848 NVARCHAR(50),
@DefaultInView_5621e848 BIT,
@ViewCellTemplate_5621e848 NVARCHAR(MAX),
@DefaultColumnWidth_5621e848 INT,
@AllowUpdateAPI_5621e848 BIT,
@AllowUpdateInView_5621e848 BIT,
@IncludeInUserSearchAPI_5621e848 BIT,
@FullTextSearchEnabled_5621e848 BIT,
@UserSearchParamFormatAPI_5621e848 NVARCHAR(500),
@IncludeInGeneratedForm_5621e848 BIT,
@GeneratedFormSection_5621e848 NVARCHAR(10),
@IsNameField_5621e848 BIT,
@RelatedEntityID_5621e848 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_5621e848 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_5621e848 BIT,
@RelatedEntityNameFieldMap_5621e848 NVARCHAR(255),
@RelatedEntityDisplayType_5621e848 NVARCHAR(20),
@EntityIDFieldName_5621e848 NVARCHAR(100),
@ScopeDefault_5621e848 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_5621e848 BIT,
@ValuesToPackWithSchema_5621e848 NVARCHAR(10),
@Status_5621e848 NVARCHAR(25),
@AutoUpdateIsNameField_5621e848 BIT,
@AutoUpdateDefaultInView_5621e848 BIT,
@AutoUpdateCategory_5621e848 BIT,
@AutoUpdateDisplayName_5621e848 BIT,
@AutoUpdateIncludeInUserSearchAPI_5621e848 BIT,
@Encrypt_5621e848 BIT,
@EncryptionKeyID_5621e848 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_5621e848 BIT,
@SendEncryptedValue_5621e848 BIT,
@IsSoftPrimaryKey_5621e848 BIT,
@IsSoftForeignKey_5621e848 BIT,
@RelatedEntityJoinFields_5621e848 NVARCHAR(MAX),
@JSONType_5621e848 NVARCHAR(255),
@JSONTypeIsArray_5621e848 BIT,
@JSONTypeDefinition_5621e848 NVARCHAR(MAX),
@UserSearchPredicateAPI_5621e848 NVARCHAR(20),
@AutoUpdateUserSearchPredicate_5621e848 BIT,
@AutoUpdateFullTextSearch_5621e848 BIT,
@AutoUpdateExtendedType_5621e848 BIT,
@IsComputed_5621e848 BIT,
@EmbeddedRecord_5621e848 NVARCHAR(MAX),
@Configuration_5621e848 NVARCHAR(MAX),
@ID_5621e848 UNIQUEIDENTIFIER
SET
  @DisplayName_5621e848 = N'Next Step'
SET
  @AutoUpdateDescription_5621e848 = 1
SET
  @IsPrimaryKey_5621e848 = 0
SET
  @IsUnique_5621e848 = 0
SET
  @ValueListType_5621e848 = N'None'
SET
  @DefaultInView_5621e848 = 1
SET
  @DefaultColumnWidth_5621e848 = 150
SET
  @AllowUpdateAPI_5621e848 = 1
SET
  @AllowUpdateInView_5621e848 = 1
SET
  @IncludeInUserSearchAPI_5621e848 = 0
SET
  @FullTextSearchEnabled_5621e848 = 0
SET
  @IncludeInGeneratedForm_5621e848 = 1
SET
  @GeneratedFormSection_5621e848 = N'Details'
SET
  @IsNameField_5621e848 = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_5621e848 = 0
SET
  @RelatedEntityDisplayType_5621e848 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_5621e848 = 1
SET
  @ValuesToPackWithSchema_5621e848 = N'Auto'
SET
  @Status_5621e848 = N'Active'
SET
  @AutoUpdateIsNameField_5621e848 = 1
SET
  @AutoUpdateDefaultInView_5621e848 = 1
SET
  @AutoUpdateCategory_5621e848 = 1
SET
  @AutoUpdateDisplayName_5621e848 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_5621e848 = 1
SET
  @Encrypt_5621e848 = 0
SET
  @AllowDecryptInAPI_5621e848 = 0
SET
  @SendEncryptedValue_5621e848 = 0
SET
  @IsSoftPrimaryKey_5621e848 = 0
SET
  @IsSoftForeignKey_5621e848 = 0
SET
  @JSONTypeIsArray_5621e848 = 0
SET
  @UserSearchPredicateAPI_5621e848 = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_5621e848 = 1
SET
  @AutoUpdateFullTextSearch_5621e848 = 1
SET
  @AutoUpdateExtendedType_5621e848 = 1
SET
  @IsComputed_5621e848 = 0
SET
  @ID_5621e848 = '4C449B35-EDD6-45D0-99C0-9D2A3C55BD66' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_5621e848,
  @Description = @Description_5621e848,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_5621e848,
  @IsPrimaryKey = @IsPrimaryKey_5621e848,
  @IsUnique = @IsUnique_5621e848,
  @Category = @Category_5621e848,
  @Category_Clear = 1,
  @ValueListType = @ValueListType_5621e848,
  @ExtendedType = @ExtendedType_5621e848,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_5621e848,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_5621e848,
  @ViewCellTemplate = @ViewCellTemplate_5621e848,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_5621e848,
  @AllowUpdateAPI = @AllowUpdateAPI_5621e848,
  @AllowUpdateInView = @AllowUpdateInView_5621e848,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_5621e848,
  @FullTextSearchEnabled = @FullTextSearchEnabled_5621e848,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_5621e848,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_5621e848,
  @GeneratedFormSection = @GeneratedFormSection_5621e848,
  @IsNameField = @IsNameField_5621e848,
  @RelatedEntityID = @RelatedEntityID_5621e848,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_5621e848,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_5621e848,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_5621e848,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_5621e848,
  @EntityIDFieldName = @EntityIDFieldName_5621e848,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_5621e848,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_5621e848,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_5621e848,
  @Status = @Status_5621e848,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_5621e848,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_5621e848,
  @AutoUpdateCategory = @AutoUpdateCategory_5621e848,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_5621e848,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_5621e848,
  @Encrypt = @Encrypt_5621e848,
  @EncryptionKeyID = @EncryptionKeyID_5621e848,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_5621e848,
  @SendEncryptedValue = @SendEncryptedValue_5621e848,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_5621e848,
  @IsSoftForeignKey = @IsSoftForeignKey_5621e848,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_5621e848,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_5621e848,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_5621e848,
  @JSONTypeDefinition = @JSONTypeDefinition_5621e848,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_5621e848,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_5621e848,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_5621e848,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_5621e848,
  @IsComputed = @IsComputed_5621e848,
  @EmbeddedRecord = @EmbeddedRecord_5621e848,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_5621e848,
  @Configuration_Clear = 1,
  @ID = @ID_5621e848;

GO

-- Save MJ: User Views (core SP call only)
DECLARE @ID_fc00be66 UNIQUEIDENTIFIER,
@UserID_fc00be66 UNIQUEIDENTIFIER,
@EntityID_fc00be66 UNIQUEIDENTIFIER,
@Name_fc00be66 NVARCHAR(100),
@Description_fc00be66 NVARCHAR(MAX),
@CategoryID_fc00be66 UNIQUEIDENTIFIER,
@IsShared_fc00be66 BIT,
@IsDefault_fc00be66 BIT,
@GridState_fc00be66 NVARCHAR(MAX),
@FilterState_fc00be66 NVARCHAR(MAX),
@CustomFilterState_fc00be66 BIT,
@SmartFilterEnabled_fc00be66 BIT,
@SmartFilterPrompt_fc00be66 NVARCHAR(MAX),
@SmartFilterWhereClause_fc00be66 NVARCHAR(MAX),
@SmartFilterExplanation_fc00be66 NVARCHAR(MAX),
@WhereClause_fc00be66 NVARCHAR(MAX),
@CustomWhereClause_fc00be66 BIT,
@SortState_fc00be66 NVARCHAR(MAX),
@Thumbnail_fc00be66 NVARCHAR(MAX),
@CardState_fc00be66 NVARCHAR(MAX),
@DisplayState_fc00be66 NVARCHAR(MAX),
@ViewTypeID_fc00be66 UNIQUEIDENTIFIER
SET
  @ID_fc00be66 = 'a11dea15-0001-4e71-b0a8-3f17c5e2d803'
SET
  @UserID_fc00be66 = 'ECAFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @EntityID_fc00be66 = '79148DE5-7F99-44AC-ACD4-5EE7BA93D354'
SET
  @Name_fc00be66 = N'Sales: Pipeline'
SET
  @Description_fc00be66 = N'Working columns for the deal pipeline: customer, stage, amount, probability, close, owner, forecast.'
SET
  @IsShared_fc00be66 = 1
SET
  @IsDefault_fc00be66 = 0
SET
  @GridState_fc00be66 = N'{"sortSettings":[{"field":"ExpectedCloseDate","dir":"asc"}],"columnSettings":[{"Name":"Name","DisplayName":"Deal","orderIndex":0,"width":260,"pinned":"left"},{"Name":"DealNumber","DisplayName":"Number","orderIndex":1,"width":120},{"Name":"Account","DisplayName":"Customer","orderIndex":2,"width":180},{"Name":"Pipeline","DisplayName":"Pipeline","orderIndex":3,"width":140},{"Name":"PipelineStage","DisplayName":"Stage","orderIndex":4,"width":130},{"Name":"DealStatusType","DisplayName":"Status","orderIndex":5,"width":110,"format":{"type":"text","conditionalRules":[{"condition":"contains","value":"Won","style":{"color":"#047857","backgroundColor":"#d1fae5","bold":true}},{"condition":"contains","value":"Lost","style":{"color":"#b45309","backgroundColor":"#fef3c7"}},{"condition":"equals","value":"Open","style":{"color":"#1d4ed8","backgroundColor":"#dbeafe"}}]}},{"Name":"Amount","DisplayName":"Amount","orderIndex":6,"width":120,"format":{"type":"currency","currencyCode":"USD","decimals":0,"align":"right"}},{"Name":"Probability","DisplayName":"Prob","orderIndex":7,"width":80,"format":{"type":"number","decimals":0,"align":"right"}},{"Name":"ExpectedCloseDate","DisplayName":"Close","orderIndex":8,"width":120,"format":{"type":"date","dateFormat":"medium"}},{"Name":"OwnerEmployee","DisplayName":"Owner","orderIndex":9,"width":140},{"Name":"ForecastCategoryType","DisplayName":"Forecast","orderIndex":10,"width":130},{"Name":"NextStep","DisplayName":"Next step","orderIndex":11,"width":200}]}'
SET
  @FilterState_fc00be66 = N'{"logic":"and","filters":[]}'
SET
  @CustomFilterState_fc00be66 = 0
SET
  @SmartFilterEnabled_fc00be66 = 0
SET
  @WhereClause_fc00be66 = N''
SET
  @CustomWhereClause_fc00be66 = 0
EXEC [${mjSchema}].spCreateUserView @ID = @ID_fc00be66,
  @UserID = @UserID_fc00be66,
  @EntityID = @EntityID_fc00be66,
  @Name = @Name_fc00be66,
  @Description = @Description_fc00be66,
  @CategoryID = @CategoryID_fc00be66,
  @CategoryID_Clear = 1,
  @IsShared = @IsShared_fc00be66,
  @IsDefault = @IsDefault_fc00be66,
  @GridState = @GridState_fc00be66,
  @FilterState = @FilterState_fc00be66,
  @CustomFilterState = @CustomFilterState_fc00be66,
  @SmartFilterEnabled = @SmartFilterEnabled_fc00be66,
  @SmartFilterPrompt = @SmartFilterPrompt_fc00be66,
  @SmartFilterPrompt_Clear = 1,
  @SmartFilterWhereClause = @SmartFilterWhereClause_fc00be66,
  @SmartFilterWhereClause_Clear = 1,
  @SmartFilterExplanation = @SmartFilterExplanation_fc00be66,
  @SmartFilterExplanation_Clear = 1,
  @WhereClause = @WhereClause_fc00be66,
  @CustomWhereClause = @CustomWhereClause_fc00be66,
  @SortState = @SortState_fc00be66,
  @SortState_Clear = 1,
  @Thumbnail = @Thumbnail_fc00be66,
  @Thumbnail_Clear = 1,
  @CardState = @CardState_fc00be66,
  @CardState_Clear = 1,
  @DisplayState = @DisplayState_fc00be66,
  @DisplayState_Clear = 1,
  @ViewTypeID = @ViewTypeID_fc00be66,
  @ViewTypeID_Clear = 1;

GO

-- Save MJ: Entities (core SP call only)
DECLARE @ParentID_908cb0aa UNIQUEIDENTIFIER,
@Name_908cb0aa NVARCHAR(255),
@NameSuffix_908cb0aa NVARCHAR(255),
@Description_908cb0aa NVARCHAR(MAX),
@AutoUpdateDescription_908cb0aa BIT,
@BaseView_908cb0aa NVARCHAR(255),
@BaseViewGenerated_908cb0aa BIT,
@VirtualEntity_908cb0aa BIT,
@TrackRecordChanges_908cb0aa BIT,
@AuditRecordAccess_908cb0aa BIT,
@AuditViewRuns_908cb0aa BIT,
@IncludeInAPI_908cb0aa BIT,
@AllowAllRowsAPI_908cb0aa BIT,
@AllowUpdateAPI_908cb0aa BIT,
@AllowCreateAPI_908cb0aa BIT,
@AllowDeleteAPI_908cb0aa BIT,
@CustomResolverAPI_908cb0aa BIT,
@AllowUserSearchAPI_908cb0aa BIT,
@FullTextSearchEnabled_908cb0aa BIT,
@FullTextCatalog_908cb0aa NVARCHAR(255),
@FullTextCatalogGenerated_908cb0aa BIT,
@FullTextIndex_908cb0aa NVARCHAR(255),
@FullTextIndexGenerated_908cb0aa BIT,
@FullTextSearchFunction_908cb0aa NVARCHAR(255),
@FullTextSearchFunctionGenerated_908cb0aa BIT,
@UserViewMaxRows_908cb0aa INT,
@spCreate_908cb0aa NVARCHAR(255),
@spUpdate_908cb0aa NVARCHAR(255),
@spDelete_908cb0aa NVARCHAR(255),
@spCreateGenerated_908cb0aa BIT,
@spUpdateGenerated_908cb0aa BIT,
@spDeleteGenerated_908cb0aa BIT,
@CascadeDeletes_908cb0aa BIT,
@DeleteType_908cb0aa NVARCHAR(10),
@AllowRecordMerge_908cb0aa BIT,
@spMatch_908cb0aa NVARCHAR(255),
@RelationshipDefaultDisplayType_908cb0aa NVARCHAR(20),
@UserFormGenerated_908cb0aa BIT,
@EntityObjectSubclassName_908cb0aa NVARCHAR(255),
@EntityObjectSubclassImport_908cb0aa NVARCHAR(255),
@PreferredCommunicationField_908cb0aa NVARCHAR(255),
@Icon_908cb0aa NVARCHAR(500),
@ScopeDefault_908cb0aa NVARCHAR(100),
@RowsToPackWithSchema_908cb0aa NVARCHAR(20),
@RowsToPackSampleMethod_908cb0aa NVARCHAR(20),
@RowsToPackSampleCount_908cb0aa INT,
@RowsToPackSampleOrder_908cb0aa NVARCHAR(MAX),
@AutoRowCountFrequency_908cb0aa INT,
@RowCount_908cb0aa BIGINT,
@RowCountRunAt_908cb0aa DATETIMEOFFSET,
@Status_908cb0aa NVARCHAR(25),
@DisplayName_908cb0aa NVARCHAR(255),
@AllowMultipleSubtypes_908cb0aa BIT,
@AutoUpdateFullTextSearch_908cb0aa BIT,
@AutoUpdateAllowUserSearchAPI_908cb0aa BIT,
@TrustServerCacheCompletely_908cb0aa BIT,
@SupportsGeoCoding_908cb0aa BIT,
@AutoUpdateSupportsGeoCoding_908cb0aa BIT,
@AllowCaching_908cb0aa BIT,
@DetectExternalChanges_908cb0aa BIT,
@ExternalDataSourceID_908cb0aa UNIQUEIDENTIFIER,
@ExternalObjectName_908cb0aa NVARCHAR(255),
@GeneratedBaseViewName_908cb0aa NVARCHAR(255),
@AllowDirectSQLInsert_908cb0aa BIT,
@AllowDirectSQLUpdate_908cb0aa BIT,
@AllowDirectSQLDelete_908cb0aa BIT,
@Configuration_908cb0aa NVARCHAR(MAX),
@ID_908cb0aa UNIQUEIDENTIFIER
SET
  @Name_908cb0aa = N'MJ_BizApps_Sales: Deals'
SET
  @Description_908cb0aa = N'A deal (opportunity). Amount is a CACHED answer from Orders.PreviewOrder carrying its own provenance, never a locally computed total — this app performs no pricing arithmetic of any kind. Closing a deal is a transaction that CREATES a contract and/or orders, not a notification that someone should.'
SET
  @AutoUpdateDescription_908cb0aa = 1
SET
  @BaseView_908cb0aa = N'vwDeals'
SET
  @BaseViewGenerated_908cb0aa = 1
SET
  @VirtualEntity_908cb0aa = 0
SET
  @TrackRecordChanges_908cb0aa = 1
SET
  @AuditRecordAccess_908cb0aa = 0
SET
  @AuditViewRuns_908cb0aa = 0
SET
  @IncludeInAPI_908cb0aa = 1
SET
  @AllowAllRowsAPI_908cb0aa = 0
SET
  @AllowUpdateAPI_908cb0aa = 1
SET
  @AllowCreateAPI_908cb0aa = 1
SET
  @AllowDeleteAPI_908cb0aa = 1
SET
  @CustomResolverAPI_908cb0aa = 0
SET
  @AllowUserSearchAPI_908cb0aa = 1
SET
  @FullTextSearchEnabled_908cb0aa = 0
SET
  @FullTextCatalogGenerated_908cb0aa = 1
SET
  @FullTextIndexGenerated_908cb0aa = 1
SET
  @FullTextSearchFunctionGenerated_908cb0aa = 1
SET
  @UserViewMaxRows_908cb0aa = 1000
SET
  @spCreateGenerated_908cb0aa = 1
SET
  @spUpdateGenerated_908cb0aa = 1
SET
  @spDeleteGenerated_908cb0aa = 1
SET
  @CascadeDeletes_908cb0aa = 0
SET
  @DeleteType_908cb0aa = N'Hard'
SET
  @AllowRecordMerge_908cb0aa = 0
SET
  @RelationshipDefaultDisplayType_908cb0aa = N'Search'
SET
  @UserFormGenerated_908cb0aa = 1
SET
  @RowsToPackWithSchema_908cb0aa = N'None'
SET
  @RowsToPackSampleMethod_908cb0aa = N'random'
SET
  @RowsToPackSampleCount_908cb0aa = 0
SET
  @Status_908cb0aa = N'Active'
SET
  @DisplayName_908cb0aa = N'Deals'
SET
  @AllowMultipleSubtypes_908cb0aa = 0
SET
  @AutoUpdateFullTextSearch_908cb0aa = 1
SET
  @AutoUpdateAllowUserSearchAPI_908cb0aa = 1
SET
  @TrustServerCacheCompletely_908cb0aa = 1
SET
  @SupportsGeoCoding_908cb0aa = 0
SET
  @AutoUpdateSupportsGeoCoding_908cb0aa = 1
SET
  @AllowCaching_908cb0aa = 0
SET
  @DetectExternalChanges_908cb0aa = 0
SET
  @AllowDirectSQLInsert_908cb0aa = 0
SET
  @AllowDirectSQLUpdate_908cb0aa = 0
SET
  @AllowDirectSQLDelete_908cb0aa = 0
SET
  @Configuration_908cb0aa = N'{
  "UI": {
    "Form": {
      "Layout": "left-nav",
      "RelatedRolePolicy": "smart"
    }
  }
}'
SET
  @ID_908cb0aa = '79148DE5-7F99-44AC-ACD4-5EE7BA93D354' EXEC [${mjSchema}].spUpdateEntity @ParentID = @ParentID_908cb0aa,
  @ParentID_Clear = 1,
  @Name = @Name_908cb0aa,
  @NameSuffix = @NameSuffix_908cb0aa,
  @NameSuffix_Clear = 1,
  @Description = @Description_908cb0aa,
  @AutoUpdateDescription = @AutoUpdateDescription_908cb0aa,
  @BaseView = @BaseView_908cb0aa,
  @BaseViewGenerated = @BaseViewGenerated_908cb0aa,
  @VirtualEntity = @VirtualEntity_908cb0aa,
  @TrackRecordChanges = @TrackRecordChanges_908cb0aa,
  @AuditRecordAccess = @AuditRecordAccess_908cb0aa,
  @AuditViewRuns = @AuditViewRuns_908cb0aa,
  @IncludeInAPI = @IncludeInAPI_908cb0aa,
  @AllowAllRowsAPI = @AllowAllRowsAPI_908cb0aa,
  @AllowUpdateAPI = @AllowUpdateAPI_908cb0aa,
  @AllowCreateAPI = @AllowCreateAPI_908cb0aa,
  @AllowDeleteAPI = @AllowDeleteAPI_908cb0aa,
  @CustomResolverAPI = @CustomResolverAPI_908cb0aa,
  @AllowUserSearchAPI = @AllowUserSearchAPI_908cb0aa,
  @FullTextSearchEnabled = @FullTextSearchEnabled_908cb0aa,
  @FullTextCatalog = @FullTextCatalog_908cb0aa,
  @FullTextCatalog_Clear = 1,
  @FullTextCatalogGenerated = @FullTextCatalogGenerated_908cb0aa,
  @FullTextIndex = @FullTextIndex_908cb0aa,
  @FullTextIndex_Clear = 1,
  @FullTextIndexGenerated = @FullTextIndexGenerated_908cb0aa,
  @FullTextSearchFunction = @FullTextSearchFunction_908cb0aa,
  @FullTextSearchFunction_Clear = 1,
  @FullTextSearchFunctionGenerated = @FullTextSearchFunctionGenerated_908cb0aa,
  @UserViewMaxRows = @UserViewMaxRows_908cb0aa,
  @spCreate = @spCreate_908cb0aa,
  @spCreate_Clear = 1,
  @spUpdate = @spUpdate_908cb0aa,
  @spUpdate_Clear = 1,
  @spDelete = @spDelete_908cb0aa,
  @spDelete_Clear = 1,
  @spCreateGenerated = @spCreateGenerated_908cb0aa,
  @spUpdateGenerated = @spUpdateGenerated_908cb0aa,
  @spDeleteGenerated = @spDeleteGenerated_908cb0aa,
  @CascadeDeletes = @CascadeDeletes_908cb0aa,
  @DeleteType = @DeleteType_908cb0aa,
  @AllowRecordMerge = @AllowRecordMerge_908cb0aa,
  @spMatch = @spMatch_908cb0aa,
  @spMatch_Clear = 1,
  @RelationshipDefaultDisplayType = @RelationshipDefaultDisplayType_908cb0aa,
  @UserFormGenerated = @UserFormGenerated_908cb0aa,
  @EntityObjectSubclassName = @EntityObjectSubclassName_908cb0aa,
  @EntityObjectSubclassName_Clear = 1,
  @EntityObjectSubclassImport = @EntityObjectSubclassImport_908cb0aa,
  @EntityObjectSubclassImport_Clear = 1,
  @PreferredCommunicationField = @PreferredCommunicationField_908cb0aa,
  @PreferredCommunicationField_Clear = 1,
  @Icon = @Icon_908cb0aa,
  @Icon_Clear = 1,
  @ScopeDefault = @ScopeDefault_908cb0aa,
  @ScopeDefault_Clear = 1,
  @RowsToPackWithSchema = @RowsToPackWithSchema_908cb0aa,
  @RowsToPackSampleMethod = @RowsToPackSampleMethod_908cb0aa,
  @RowsToPackSampleCount = @RowsToPackSampleCount_908cb0aa,
  @RowsToPackSampleOrder = @RowsToPackSampleOrder_908cb0aa,
  @RowsToPackSampleOrder_Clear = 1,
  @AutoRowCountFrequency = @AutoRowCountFrequency_908cb0aa,
  @AutoRowCountFrequency_Clear = 1,
  @RowCount = @RowCount_908cb0aa,
  @RowCount_Clear = 1,
  @RowCountRunAt = @RowCountRunAt_908cb0aa,
  @RowCountRunAt_Clear = 1,
  @Status = @Status_908cb0aa,
  @DisplayName = @DisplayName_908cb0aa,
  @AllowMultipleSubtypes = @AllowMultipleSubtypes_908cb0aa,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_908cb0aa,
  @AutoUpdateAllowUserSearchAPI = @AutoUpdateAllowUserSearchAPI_908cb0aa,
  @TrustServerCacheCompletely = @TrustServerCacheCompletely_908cb0aa,
  @SupportsGeoCoding = @SupportsGeoCoding_908cb0aa,
  @AutoUpdateSupportsGeoCoding = @AutoUpdateSupportsGeoCoding_908cb0aa,
  @AllowCaching = @AllowCaching_908cb0aa,
  @DetectExternalChanges = @DetectExternalChanges_908cb0aa,
  @ExternalDataSourceID = @ExternalDataSourceID_908cb0aa,
  @ExternalDataSourceID_Clear = 1,
  @ExternalObjectName = @ExternalObjectName_908cb0aa,
  @ExternalObjectName_Clear = 1,
  @GeneratedBaseViewName = @GeneratedBaseViewName_908cb0aa,
  @GeneratedBaseViewName_Clear = 1,
  @AllowDirectSQLInsert = @AllowDirectSQLInsert_908cb0aa,
  @AllowDirectSQLUpdate = @AllowDirectSQLUpdate_908cb0aa,
  @AllowDirectSQLDelete = @AllowDirectSQLDelete_908cb0aa,
  @Configuration = @Configuration_908cb0aa,
  @ID = @ID_908cb0aa;

GO

-- Delete MJ: Action Params (core SP call only)
EXEC [${mjSchema}].[spDeleteActionParam] @ID = '5A1E5000-0000-4000-8000-000000000102';

GO

-- Delete MJ: Actions (core SP call only)
EXEC [${mjSchema}].[spDeleteAction] @ID = '5A1E5000-0000-4000-8000-000000000101';

GO

-- Delete MJ: Scheduled Jobs (core SP call only)
EXEC [${mjSchema}].[spDeleteScheduledJob] @ID = '5A1E5000-0000-4000-8000-000000000201';

GO


-- End of SQL Logging Session
-- Session ID: bfccc621-6364-4735-912a-5af2908853d4
-- Completed: 2026-09-02T05:11:44.411Z
-- Duration: 4843ms
-- Total Statements: 17
